<!doctype html>
<html lang="zh-Hant-TW">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="《財務時間序列分析》R 線上附錄：R01：R、tidyverse 與手動 OLS">
  <title>R01：R、tidyverse 與手動 OLS｜財務時間序列分析</title>
  <link rel="stylesheet" href="assets/site.css">
  <script>
    window.MathJax = {
      tex: {inlineMath: [['$', '$'], ['\\(', '\\)']], displayMath: [['$$', '$$'], ['\\[', '\\]']]},
      svg: {fontCache: 'local'},
      options: {skipHtmlTags: ['script', 'noscript', 'style', 'textarea', 'pre', 'code']}
    };
  </script>
  <script defer src="assets/mathjax-loader.js"></script>
  <script defer src="assets/site.js"></script>
</head>
<body>
  <a class="skip-link" href="#main-content">跳到主要內容</a>
  <header class="site-header">
    <button class="menu-button" type="button" aria-controls="site-navigation" aria-expanded="false">目錄</button>
    <a class="brand" href="index.html"><span>財務時間序列分析</span><small>R 線上附錄</small></a>
    <a class="policy-link" href="data-policy.html">資料說明</a>
  </header>
  <div class="layout">
    <nav id="site-navigation" class="sidebar" aria-label="全部線上附錄">
      <p class="sidebar-title">線上附錄</p>
      <ol><li><a href="index.html">首頁</a></li>
<li><a href="data.html">實證資料下載</a></li>
<li><a href="data-policy.html">資料來源與重現說明</a></li>
<li><a href="R00_environment_reproducibility.html">R00　環境、專案與可重現研究</a></li>
<li><a href="R01_r_tidyverse_manual_ols.html" aria-current="page" class="active">R01　R、tidyverse 與手動 OLS</a></li>
<li><a href="R02_prices_dates_returns.html">R02　價格、日期與報酬率</a></li>
<li><a href="R03_distributions_heavy_tails.html">R03　分配、厚尾與實證特徵</a></li>
<li><a href="R04_ar_ma_arma_simulation.html">R04　AR、MA、ARMA 與真實報酬的 ACF</a></li>
<li><a href="R05_arma_estimation_diagnostics_forecasting.html">R05　AAPL 的 ARMA 估計、診斷與預測</a></li>
<li><a href="R06_leak_free_out_of_sample_evaluation.html">R06　TWD／JPY 的無資料洩漏樣本外評估</a></li>
<li><a href="R07_unit_roots_differencing_breaks.html">R07　TWD／JPY 的單根、差分與結構變動</a></li>
<li><a href="R08_arch_garch_asymmetry_forecasting.html">R08　AAPL 的 ARCH、GARCH、非對稱波動與預測</a></li>
<li><a href="R09_portfolio_capm_factors.html">R09　美國十產業投資組合、CAPM 與 Fama–French 三因子</a></li>
<li><a href="R10_pca_factor_analysis.html">R10　真實股票報酬的 PCA、低秩重建與因子分析</a></li>
<li><a href="R11_sp500_pca_corrected.html">R11　S&amp;P 500 平衡子樣本的 PCA 與跨股票落後值修正</a></li>
<li><a href="R12_taiwan_dcc_icapm_case_study.html">R12　臺灣 DCC–ICAPM 的第二階段個案研究</a></li>
<li><a href="R13_regularization.html">R13　Ridge、LASSO、Elastic Net 與 post-LASSO</a></li>
<li><a href="R14_financial_factor_selection.html">R14　機器學習的金融因子選擇</a></li>
<li><a href="R15_double_selection_dml.html">R15　加州學校資料的雙重選擇與 DML 式殘差化</a></li>
<li><a href="R16_var_irf.html">R16　VAR、識別與衝擊反應函數</a></li>
<li><a href="R17_cointegration_vecm.html">R17　共整合、Johansen 檢定與 VECM</a></li>
<li><a href="R18_local_projection_irf.html">R18　VAR、局部投影與進階 IRF</a></li></ol>
    </nav>
    <main id="main-content" class="content">
      <div class="publication-note">
        想自己重算，可以從頁首下載 R Markdown 與執行結果。所有實證例都使用隨書提供的固定資料；
        檔案來源、變數單位與已知限制請見<a href="data-policy.html">資料來源與重現說明</a>。
      </div>
      <article>
        <header class="article-header"><p class="eyebrow">《財務時間序列分析》線上附錄</p><h1>R01：R、tidyverse 與手動 OLS</h1><div class="source-links" aria-label="下載本頁檔案"><a href="source/R01_r_tidyverse_manual_ols.Rmd">下載 R Markdown</a><a href="source/R01_r_tidyverse_manual_ols.md">下載執行結果（Markdown）</a></div></header>
        <p>本附錄對應第 1 章，要回答一個適合初學 R、也很適合檢查公式的問題：把普通最小平方法（ordinary least squares, OLS）的矩陣公式直接寫成程式，會不會得到與 <code>lm()</code> 相同的係數？我們以 AAPL 當日報酬為應變數，將 MSFT 與 NVDA 的等權平均當日報酬作為解釋變數，依序完成資料整理、手動 OLS、套件結果比較與殘差診斷。</p>
<p>資料共有 2,384 個共同交易日，期間為 2013-01-03 至 2022-06-22。每一列是一個交易日，每一欄是一檔股票的日簡單報酬，報酬以小數表示；例如 0.01 代表 1%。解釋變數使用的是與 AAPL 同一天收盤後才完整可得的報酬，因此這裡研究的是同日線性關係，不是盤前或即時預測。全樣本都用於這項代數練習，沒有另分訓練期、驗證期與測試期，也沒有足以支持因果解讀的識別設計。</p>
<pre><code class="language-r">knitr::opts_chunk$set(
  echo = TRUE, message = FALSE, warning = FALSE,
  fig.width = 7, fig.height = 4.5
)
stopifnot(requireNamespace(&quot;dplyr&quot;, quietly = TRUE))
stopifnot(requireNamespace(&quot;tibble&quot;, quietly = TRUE))
library(dplyr)
</code></pre>
<pre><code>## 
## Attaching package: 'dplyr'
</code></pre>
<pre><code>## The following objects are masked from 'package:stats':
## 
##     filter, lag
</code></pre>
<pre><code>## The following objects are masked from 'package:base':
## 
##     intersect, setdiff, setequal, union
</code></pre>
<pre><code class="language-r">library(tibble)

root_candidates &lt;- c(&quot;.&quot;, &quot;..&quot;)
is_root &lt;- vapply(root_candidates, function(x) {
  file.exists(file.path(x, &quot;main.tex&quot;))
}, logical(1))
stopifnot(any(is_root))
project_root &lt;- root_candidates[which(is_root)[1]]
project_path &lt;- function(...) file.path(project_root, ...)
</code></pre>
<h2 id="_1">先把觀察單位與排序確認清楚<a class="headerlink" href="#_1" title="Permanent link">#</a></h2>
<p>讀檔後先只留下本例需要的日期與三檔股票。日期轉成 R 的 <code>Date</code> 類別後再排序，才能確定第 $t-1$ 列真的早於第 $t$ 列。固定面板已保留三檔股票都有報酬的共同交易日，所以這一頁不做填補或刪除缺值。</p>
<pre><code class="language-r">data_path &lt;- project_path(
  &quot;data&quot;, &quot;processed&quot;, &quot;sp500_returns_balanced_2013_2022.csv&quot;
)
manifest_path &lt;- project_path(&quot;data&quot;, &quot;processed&quot;, &quot;manifest.csv&quot;)
stopifnot(file.exists(data_path), file.exists(manifest_path))

raw &lt;- read.csv(data_path, check.names = FALSE)
returns &lt;- raw |&gt;
  transmute(
    date = as.Date(date),
    AAPL = as.numeric(AAPL),
    MSFT = as.numeric(MSFT),
    NVDA = as.numeric(NVDA)
  ) |&gt;
  arrange(date)

# 若日期重複、順序錯誤或任一欄缺值，先回到資料入口處理。
stopifnot(!anyNA(returns), !anyDuplicated(returns$date))
stopifnot(all(diff(returns$date) &gt; 0))
glimpse(returns)
</code></pre>
<pre><code>## Rows: 2,384
## Columns: 4
## $ date &lt;date&gt; 2013-01-03, 2013-01-04, 2013-01-07, 2013-01-08, 2013-01-09, 2013…
## $ AAPL &lt;dbl&gt; -0.012622072, -0.027854471, -0.005882822, 0.002691439, -0.0156289…
## $ MSFT &lt;dbl&gt; -0.0133961372, -0.0187154612, -0.0018699229, -0.0052453126, 0.005…
## $ NVDA &lt;dbl&gt; 0.0007860068, 0.0329928166, -0.0288975086, -0.0219260948, -0.0224…
</code></pre>
<p><code>glimpse()</code> 應顯示 2,384 列與四個欄位；三個報酬欄都是數值，日期則為 <code>Date</code>。資料由原課程價格長表建立，建檔時先在每一檔股票內依日期計算報酬，再保留 89 檔都有觀察值的共同交易日。來源、建檔方式與 MD5 記錄見 <code>data/DATA_SOURCES.md</code>。</p>
<h2 id="_2">向量、資料框與管線<a class="headerlink" href="#_2" title="Permanent link">#</a></h2>
<p>接下來先熟悉兩個最常用的 R 物件。<code>first_five</code> 是只含五個數字的向量，<code>returns</code> 則是每列代表一個交易日的資料框；先分清楚物件的形狀，後面建立設計矩陣時才不會把列與欄顛倒。</p>
<pre><code class="language-r">first_five &lt;- returns$AAPL[1:5]
object_summary &lt;- tibble(
  object = c(&quot;first_five&quot;, &quot;returns&quot;),
  class = c(class(first_five)[1], class(returns)[1]),
  length_or_rows = c(length(first_five), nrow(returns))
)
object_summary
</code></pre>
<pre><code>## # A tibble: 2 × 3
##   object     class      length_or_rows
##   &lt;chr&gt;      &lt;chr&gt;               &lt;int&gt;
## 1 first_five numeric                 5
## 2 returns    data.frame           2384
</code></pre>
<p>現在用 <code>mutate()</code> 建立 MSFT 與 NVDA 的等權平均報酬 <code>tech_equal</code>，再用 <code>summarise()</code> 按年度整理 AAPL 的觀察值數、平均數與標準差。年度表的每一列是一個曆年；因原檔已是簡單報酬，<code>mean_aapl</code> 與 <code>sd_aapl</code> 仍以小數表示，而不是百分比。</p>
<pre><code class="language-r">analysis_df &lt;- returns |&gt;
  mutate(
    tech_equal = (MSFT + NVDA) / 2,
    year = as.integer(format(date, &quot;%Y&quot;))
  )

annual_summary &lt;- analysis_df |&gt;
  group_by(year) |&gt;
  summarise(
    observations = n(),
    mean_aapl = mean(AAPL),
    sd_aapl = sd(AAPL),
    .groups = &quot;drop&quot;
  )
annual_summary
</code></pre>
<pre><code>## # A tibble: 10 × 4
##     year observations  mean_aapl sd_aapl
##    &lt;int&gt;        &lt;int&gt;      &lt;dbl&gt;   &lt;dbl&gt;
##  1  2013          251  0.000347   0.0179
##  2  2014          252  0.00145    0.0136
##  3  2015          252  0.0000199  0.0168
##  4  2016          252  0.000575   0.0147
##  5  2017          251  0.00164    0.0111
##  6  2018          251 -0.0000573  0.0181
##  7  2019          252  0.00266    0.0165
##  8  2020          253  0.00281    0.0294
##  9  2021          252  0.00131    0.0158
## 10  2022          118 -0.00202    0.0227
</code></pre>
<p>這張表先讓我們看出各年交易日數與波動是否大致合理。若某一年觀察值突然很少，應先檢查資料涵蓋與共同交易日規則，再進入迴歸；年度平均數的正負也只是樣本描述，不宜當作穩定的未來報酬率。</p>
<h2 id="ols">手動 OLS<a class="headerlink" href="#ols" title="Permanent link">#</a></h2>
<p>令 $y$ 為 AAPL 當日報酬，$x$ 為 MSFT、NVDA 的等權平均當日報酬。設計矩陣 $X$ 的每一列對應一個共同交易日，第一欄全為 1，用來估計截距，第二欄才是 <code>tech_equal</code>。在計算 $(X^\top X)^{-1}X^\top y$ 以前，先確認 $X$ 的列數與 $y$ 的長度相同，而且兩欄線性獨立。</p>
<pre><code class="language-r">y &lt;- analysis_df$AAPL
X &lt;- cbind(Intercept = 1, tech_equal = analysis_df$tech_equal)

# 維度不合或設計矩陣不滿秩時，OLS 公式不能照寫下去。
stopifnot(nrow(X) == length(y), qr(X)$rank == ncol(X))

beta_manual &lt;- solve(crossprod(X), crossprod(X, y))
fitted_manual &lt;- as.numeric(X %*% beta_manual)
residual_manual &lt;- y - fitted_manual

tibble(
  term = rownames(beta_manual),
  estimate = as.numeric(beta_manual)
)
</code></pre>
<pre><code>## # A tibble: 2 × 2
##   term       estimate
##   &lt;chr&gt;         &lt;dbl&gt;
## 1 Intercept  0.000124
## 2 tech_equal 0.569
</code></pre>
<p><code>crossprod(X)</code> 等於 $X^\top X$，<code>crossprod(X, y)</code> 等於 $X^\top y$。輸出中的截距約為 0.000124，斜率約為 0.5693。就這份樣本而言，MSFT 與 NVDA 的等權平均當日報酬每增加 1 個百分點，AAPL 的線性投影值約增加 0.569 個百分點；這是同日共同波動的條件關聯，不表示前兩檔股票造成 AAPL 上漲。正式計算通常偏好 QR 分解，因為直接解正規方程式在近共線時較不穩定；此處保留矩陣公式，是為了讓課文中的推導與 R 運算一一對上。</p>
<h2 id="lm-qr">用 <code>lm()</code> 與 QR 分解比較同一個答案<a class="headerlink" href="#lm-qr" title="Permanent link">#</a></h2>
<p>手動結果算出後，再讓 <code>qr.solve()</code> 與 <code>lm()</code> 解同一個問題。三欄係數的名稱與次序必須一致，否則即使數字相近，也可能是在比較不同參數。</p>
<pre><code class="language-r">fit_lm &lt;- lm(AAPL ~ tech_equal, data = analysis_df)
beta_qr &lt;- qr.solve(X, y)

comparison &lt;- tibble(
  term = names(coef(fit_lm)),
  manual = as.numeric(beta_manual),
  qr = as.numeric(beta_qr),
  lm = as.numeric(coef(fit_lm))
)
comparison
</code></pre>
<pre><code>## # A tibble: 2 × 4
##   term          manual       qr       lm
##   &lt;chr&gt;          &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;
## 1 (Intercept) 0.000124 0.000124 0.000124
## 2 tech_equal  0.569    0.569    0.569
</code></pre>
<pre><code class="language-r"># 三種演算法應在浮點計算容許範圍內得到相同係數。
stopifnot(
  isTRUE(all.equal(as.numeric(beta_manual), as.numeric(beta_qr))),
  isTRUE(all.equal(as.numeric(beta_manual), as.numeric(coef(fit_lm))))
)
</code></pre>
<p><code>comparison</code> 的三個係數欄應重合。這項結果說明我們正確地把 OLS 公式翻成 R；它沒有比較模型好壞，也沒有替殘差的時間序列性質背書。</p>
<h2 id="_3">正規方程式與配適分解<a class="headerlink" href="#_3" title="Permanent link">#</a></h2>
<p>含截距的 OLS 殘差應與設計矩陣的每一欄正交。這裡直接計算 $X^\top \hat e$，也把總平方和分成模型解釋部分與殘差平方和，確認係數、配適值與殘差彼此一致。</p>
<pre><code class="language-r">orthogonality &lt;- as.numeric(crossprod(X, residual_manual))
names(orthogonality) &lt;- colnames(X)
orthogonality
</code></pre>
<pre><code>##    Intercept   tech_equal 
## 5.342948e-16 2.107689e-16
</code></pre>
<pre><code class="language-r">stopifnot(max(abs(orthogonality)) &lt; 1e-10)

sst &lt;- sum((y - mean(y))^2)
sse &lt;- sum(residual_manual^2)
ssr &lt;- sum((fitted_manual - mean(y))^2)
c(SST = sst, explained = ssr, SSE = sse, difference = sst - ssr - sse)
</code></pre>
<pre><code>##           SST     explained           SSE    difference 
##  7.771318e-01  2.989755e-01  4.781562e-01 -4.996004e-16
</code></pre>
<p><code>orthogonality</code> 的兩個數應非常接近零，平方和表中的 <code>difference</code> 也應只剩浮點誤差。若差距明顯，應先檢查是否漏了截距、資料列是否錯位，或配適值與殘差是否來自同一個模型。</p>
<h2 id="_4">在計算以前先決定如何處理缺值<a class="headerlink" href="#_4" title="Permanent link">#</a></h2>
<p>固定面板目前沒有缺值，但換成別份資料時，刪除觀察值可能改變樣本期間與研究對象。以下函數的一般設定是遇到缺值就停止；只有呼叫者把 <code>allow_drop</code> 明確設為 <code>TRUE</code> 時，才保留指定欄位都完整的列。把決定集中在資料準備階段，比在每一個統計量中分別加入 <code>na.rm = TRUE</code> 更容易看出實際用了哪些觀察值。</p>
<pre><code class="language-r">prepare_complete &lt;- function(data, columns, allow_drop = FALSE) {
  stopifnot(all(columns %in% names(data)))
  ok &lt;- complete.cases(data[, columns, drop = FALSE])
  # 先要求研究者選擇處理方式，避免各函數各自悄悄丟掉不同列。
  if (!all(ok) &amp;&amp; !allow_drop) {
    stop(&quot;指定欄位含缺值；請決定刪除、填補或修正來源。&quot;)
  }
  data[ok, , drop = FALSE]
}

toy &lt;- tibble(y = c(1, 2, NA), x = c(0, 1, 2))
expected_error &lt;- try(
  prepare_complete(toy, c(&quot;y&quot;, &quot;x&quot;)),
  silent = TRUE
)
inherits(expected_error, &quot;try-error&quot;)
</code></pre>
<pre><code>## [1] TRUE
</code></pre>
<pre><code class="language-r">prepare_complete(toy, c(&quot;y&quot;, &quot;x&quot;), allow_drop = TRUE)
</code></pre>
<pre><code>## # A tibble: 2 × 2
##       y     x
##   &lt;dbl&gt; &lt;dbl&gt;
## 1     1     0
## 2     2     1
</code></pre>
<p>第一次呼叫應得到預期錯誤，第二次則只留下前兩列。實際研究若允許刪除，還要報告刪除了多少列、落在哪些日期，以及缺值是否可能與市場狀況有關。</p>
<h2 id="_5">診斷圖<a class="headerlink" href="#_5" title="Permanent link">#</a></h2>
<p>係數相同只代表三種計算法一致，還不能回答線性模型是否充分。殘差對配適值圖用來找非線性或變異程度改變，常態 Q–Q 圖則讓我們觀察尾端是否偏離常態；兩張圖的每一點仍對應一個共同交易日。</p>
<pre><code class="language-r">par(mfrow = c(1, 2))
plot(
  fitted_manual, residual_manual,
  xlab = &quot;配適值&quot;, ylab = &quot;殘差&quot;,
  pch = 16, cex = 0.45, col = &quot;#173B57&quot;
)
abline(h = 0, lty = 2, col = &quot;#A34045&quot;)
qqnorm(residual_manual, pch = 16, cex = 0.45, col = &quot;#173B57&quot;)
qqline(residual_manual, col = &quot;#A34045&quot;, lwd = 2)
</code></pre>
<p><img alt="OLS 殘差與配適值；此圖只診斷線性投影，不代表預測或因果。" src="./R01_r_tidyverse_manual_ols_files/figure-gfm/diagnostics-1.png"></p>
<pre><code class="language-r">par(mfrow = c(1, 1))
</code></pre>
<p>圖形若呈現厚尾、極端點或波動群聚，OLS 係數的代數結果仍成立，但傳統獨立同分配標準誤便未必合適。下一步應檢查殘差的自相關與條件異質變異，並視研究目的採用時間序列穩健推論或重新指定模型。</p>
<h2 id="_6">這份練習回答了什麼<a class="headerlink" href="#_6" title="Permanent link">#</a></h2>
<p>這份固定資料顯示 AAPL 與另外兩檔大型科技股的同日報酬具有正向線性關聯，而且手動公式、QR 分解與 <code>lm()</code> 給出相同係數。它還沒有告訴我們這項關聯在未來是否穩定，也沒有因果含意。若要把問題改成預測，解釋變數必須在預測起點已經可得，例如用第 $t$ 日資訊預測第 $t+1$ 日報酬，並依第 8 章以時間排序的訓練期、驗證期與測試期評估。</p>
      </article>
      <nav class="pager" aria-label="前後附錄"><a rel="prev" href="R00_environment_reproducibility.html">← 環境、專案與可重現研究</a><a rel="next" href="R02_prices_dates_returns.html">價格、日期與報酬率 →</a></nav>
      <footer>© 陳釗而　《財務時間序列分析》</footer>
    </main>
    <aside class="page-toc"><h2>本頁目錄</h2><div class="toc">
<ul>
<li><a href="#_1">先把觀察單位與排序確認清楚</a></li>
<li><a href="#_2">向量、資料框與管線</a></li>
<li><a href="#ols">手動 OLS</a></li>
<li><a href="#lm-qr">用 lm() 與 QR 分解比較同一個答案</a></li>
<li><a href="#_3">正規方程式與配適分解</a></li>
<li><a href="#_4">在計算以前先決定如何處理缺值</a></li>
<li><a href="#_5">診斷圖</a></li>
<li><a href="#_6">這份練習回答了什麼</a></li>
</ul>
</div>
</aside>
  </div>
</body>
</html>
