<!doctype html>
<html lang="zh-Hant-TW">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="《財務時間序列分析》R 線上附錄：R03：分配、厚尾與實證特徵">
  <title>R03：分配、厚尾與實證特徵｜財務時間序列分析</title>
  <link rel="stylesheet" href="assets/site.css">
  <script>
    window.MathJax = {
      tex: {inlineMath: [['$', '$'], ['\\(', '\\)']], displayMath: [['$$', '$$'], ['\\[', '\\]']]},
      svg: {fontCache: 'local'},
      options: {skipHtmlTags: ['script', 'noscript', 'style', 'textarea', 'pre', 'code']}
    };
  </script>
  <script defer src="assets/mathjax-loader.js"></script>
  <script defer src="assets/site.js"></script>
</head>
<body>
  <a class="skip-link" href="#main-content">跳到主要內容</a>
  <header class="site-header">
    <button class="menu-button" type="button" aria-controls="site-navigation" aria-expanded="false">目錄</button>
    <a class="brand" href="index.html"><span>財務時間序列分析</span><small>R 線上附錄</small></a>
    <a class="policy-link" href="data-policy.html">資料說明</a>
  </header>
  <div class="layout">
    <nav id="site-navigation" class="sidebar" aria-label="全部線上附錄">
      <p class="sidebar-title">線上附錄</p>
      <ol><li><a href="index.html">首頁</a></li>
<li><a href="data.html">實證資料下載</a></li>
<li><a href="data-policy.html">資料來源與重現說明</a></li>
<li><a href="R00_environment_reproducibility.html">R00　環境、專案與可重現研究</a></li>
<li><a href="R01_r_tidyverse_manual_ols.html">R01　R、tidyverse 與手動 OLS</a></li>
<li><a href="R02_prices_dates_returns.html">R02　價格、日期與報酬率</a></li>
<li><a href="R03_distributions_heavy_tails.html" aria-current="page" class="active">R03　分配、厚尾與實證特徵</a></li>
<li><a href="R04_ar_ma_arma_simulation.html">R04　AR、MA、ARMA 與真實報酬的 ACF</a></li>
<li><a href="R05_arma_estimation_diagnostics_forecasting.html">R05　AAPL 的 ARMA 估計、診斷與預測</a></li>
<li><a href="R06_leak_free_out_of_sample_evaluation.html">R06　TWD／JPY 的無資料洩漏樣本外評估</a></li>
<li><a href="R07_unit_roots_differencing_breaks.html">R07　TWD／JPY 的單根、差分與結構變動</a></li>
<li><a href="R08_arch_garch_asymmetry_forecasting.html">R08　AAPL 的 ARCH、GARCH、非對稱波動與預測</a></li>
<li><a href="R09_portfolio_capm_factors.html">R09　美國十產業投資組合、CAPM 與 Fama–French 三因子</a></li>
<li><a href="R10_pca_factor_analysis.html">R10　真實股票報酬的 PCA、低秩重建與因子分析</a></li>
<li><a href="R11_sp500_pca_corrected.html">R11　S&amp;P 500 平衡子樣本的 PCA 與跨股票落後值修正</a></li>
<li><a href="R12_taiwan_dcc_icapm_case_study.html">R12　臺灣 DCC–ICAPM 的第二階段個案研究</a></li>
<li><a href="R13_regularization.html">R13　Ridge、LASSO、Elastic Net 與 post-LASSO</a></li>
<li><a href="R14_financial_factor_selection.html">R14　機器學習的金融因子選擇</a></li>
<li><a href="R15_double_selection_dml.html">R15　加州學校資料的雙重選擇與 DML 式殘差化</a></li>
<li><a href="R16_var_irf.html">R16　VAR、識別與衝擊反應函數</a></li>
<li><a href="R17_cointegration_vecm.html">R17　共整合、Johansen 檢定與 VECM</a></li>
<li><a href="R18_local_projection_irf.html">R18　VAR、局部投影與進階 IRF</a></li></ol>
    </nav>
    <main id="main-content" class="content">
      <div class="publication-note">
        想自己重算，可以從頁首下載 R Markdown 與執行結果。所有實證例都使用隨書提供的固定資料；
        檔案來源、變數單位與已知限制請見<a href="data-policy.html">資料來源與重現說明</a>。
      </div>
      <article>
        <header class="article-header"><p class="eyebrow">《財務時間序列分析》線上附錄</p><h1>R03：分配、厚尾與實證特徵</h1><div class="source-links" aria-label="下載本頁檔案"><a href="source/R03_distributions_heavy_tails.Rmd">下載 R Markdown</a><a href="source/R03_distributions_heavy_tails.md">下載執行結果（Markdown）</a></div></header>
        <p>本附錄對應第 3–4 章，要回答兩個彼此相關的問題：金融報酬的尾端是否比常態分配厚，以及大幅波動是否會在時間上成群出現？我們先用固定種子模擬常態與標準化 Student-$t$ 分配，確認「變異數相同，尾端仍可很不一樣」；再把同一套描述工具用在兩組真實日簡單報酬上。</p>
<p>第一組資料是 1986–2008 年的 Microsoft（MSFT），每一列代表一個交易日；第二組是由 89 檔股票組成的 2013–2022 年等權教學投資組合，每一列先記錄同一共同交易日的 89 個個股報酬，再取橫斷面平均。MSFT 資料源自 Ruey S. Tsay 教科書網站的 <code>d-msft8608.txt</code>，股票面板源自原課程 S&amp;P 500 價格檔；固定版本與建置方式見 <code>data/DATA_SOURCES.md</code>。</p>
<p>兩組報酬都以小數表示，0.01 代表 1%。等權序列是教學用組合，不是官方 S&amp;P 500 指數，也沒有校正成分股生存者偏誤。本頁使用完整歷史樣本做分配與相依性描述，不進行預測，因此不分訓練期、驗證期與測試期；結果也沒有識別任何市場事件對報酬的因果效果。</p>
<pre><code class="language-r">knitr::opts_chunk$set(
  echo = TRUE, message = FALSE, warning = FALSE,
  fig.width = 8, fig.height = 5,
  dev = &quot;ragg_png&quot;, dpi = 144,
  dev.args = list(background = &quot;white&quot;)
)
set.seed(20260716)

root_candidates &lt;- c(&quot;.&quot;, &quot;..&quot;)
is_root &lt;- vapply(root_candidates, function(x) {
  file.exists(file.path(x, &quot;main.tex&quot;))
}, logical(1))
stopifnot(any(is_root))
project_root &lt;- root_candidates[which(is_root)[1]]
project_path &lt;- function(...) file.path(project_root, ...)

stopifnot(
  requireNamespace(&quot;ragg&quot;, quietly = TRUE),
  requireNamespace(&quot;systemfonts&quot;, quietly = TRUE)
)
cwtex_file &lt;- project_path(&quot;assets&quot;, &quot;fonts&quot;, &quot;cwTeXQKai-Medium.ttf&quot;)
stopifnot(file.exists(cwtex_file))
if (!&quot;cwTeX Online&quot; %in% systemfonts::registry_fonts()$family) {
  systemfonts::register_font(&quot;cwTeX Online&quot;, cwtex_file)
}
plot_family &lt;- &quot;cwTeX Online&quot;
</code></pre>
<h2 id="jarquebera">描述統計與 Jarque–Bera 函數<a class="headerlink" href="#jarquebera" title="Permanent link">#</a></h2>
<p>先寫兩個小函數，目的是讓每一個輸出都能與公式對上。<code>sample_moments()</code> 接受一條報酬序列，輸出有效觀察值數、平均數、標準差、偏態、峰度與尾端分位數；<code>jarque_bera()</code> 再用偏態與超額峰度組成檢定統計量。以下峰度採用「常態分配等於 3」的定義，超額峰度則是峰度減 3。有限樣本偏態與峰度有不同修正版本，因此比較手動版與套件版以前，必須先確認定義。</p>
<pre><code class="language-r">sample_moments &lt;- function(x) {
  # 描述同一條序列時使用相同的有限值樣本，避免各統計量樣本數不同。
  x &lt;- x[is.finite(x)]
  centered &lt;- x - mean(x)
  m2 &lt;- mean(centered^2)
  m3 &lt;- mean(centered^3)
  m4 &lt;- mean(centered^4)
  c(
    n = length(x),
    mean = mean(x),
    sd = sd(x),
    skewness = m3 / m2^(3 / 2),
    kurtosis = m4 / m2^2,
    excess_kurtosis = m4 / m2^2 - 3,
    q01 = unname(quantile(x, 0.01)),
    q05 = unname(quantile(x, 0.05)),
    median = median(x),
    q95 = unname(quantile(x, 0.95)),
    q99 = unname(quantile(x, 0.99))
  )
}

jarque_bera &lt;- function(x) {
  m &lt;- sample_moments(x)
  # 此處使用教科書中的 iid 漸近式；時間相依性稍後另做診斷。
  statistic &lt;- m[&quot;n&quot;] * (
    m[&quot;skewness&quot;]^2 / 6 + m[&quot;excess_kurtosis&quot;]^2 / 24
  )
  c(
    statistic = unname(statistic),
    p_value_iid_asymptotic = unname(
      pchisq(statistic, 2, lower.tail = FALSE)
    )
  )
}
</code></pre>
<h2 id="_1">先用已知分配看懂「厚尾」<a class="headerlink" href="#_1" title="Permanent link">#</a></h2>
<p>模擬的好處是母體分配已知，可以先排除資料建置與模型選擇的干擾。自由度 5 的 Student-$t$ 變異數是 $5/(5-2)$；除以理論標準差後，它與標準常態具有相同變異數，但尾端機率仍較高。這一段要觀察的是峰度、尾端分位數與直方圖形狀，不是檢定金融市場。</p>
<pre><code class="language-r">n_sim &lt;- 10000L
normal_draw &lt;- rnorm(n_sim)
# 標準化後兩組理論變異數相同，尾端差異才不會只是尺度造成。
t5_draw &lt;- rt(n_sim, df = 5) / sqrt(5 / 3)

simulation_summary &lt;- rbind(
  Normal = sample_moments(normal_draw),
  Student_t5 = sample_moments(t5_draw)
)
knitr::kable(round(simulation_summary, 4))
</code></pre>
<table>
<thead>
<tr>
<th style="text-align: left;"></th>
<th style="text-align: right;">n</th>
<th style="text-align: right;">mean</th>
<th style="text-align: right;">sd</th>
<th style="text-align: right;">skewness</th>
<th style="text-align: right;">kurtosis</th>
<th style="text-align: right;">excess_kurtosis</th>
<th style="text-align: right;">q01</th>
<th style="text-align: right;">q05</th>
<th style="text-align: right;">median</th>
<th style="text-align: right;">q95</th>
<th style="text-align: right;">q99</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align: left;">Normal</td>
<td style="text-align: right;">10000</td>
<td style="text-align: right;">0.0101</td>
<td style="text-align: right;">1.0136</td>
<td style="text-align: right;">-0.0016</td>
<td style="text-align: right;">3.0640</td>
<td style="text-align: right;">0.0640</td>
<td style="text-align: right;">-2.4048</td>
<td style="text-align: right;">-1.6583</td>
<td style="text-align: right;">0.0099</td>
<td style="text-align: right;">1.6794</td>
<td style="text-align: right;">2.3828</td>
</tr>
<tr>
<td style="text-align: left;">Student_t5</td>
<td style="text-align: right;">10000</td>
<td style="text-align: right;">0.0007</td>
<td style="text-align: right;">1.0129</td>
<td style="text-align: right;">-0.1179</td>
<td style="text-align: right;">8.1864</td>
<td style="text-align: right;">5.1864</td>
<td style="text-align: right;">-2.6003</td>
<td style="text-align: right;">-1.5806</td>
<td style="text-align: right;">0.0158</td>
<td style="text-align: right;">1.5817</td>
<td style="text-align: right;">2.6540</td>
</tr>
</tbody>
</table>
<p>樣本平均數與變異數會因這一次亂數抽樣略有誤差。標準化 Student-$t_5$ 的 1% 與 99% 分位數通常比常態分位數離零更遠，但 5% 與 95% 分位數反而更靠近零，不能籠統地說所有尾端分位數都更遠。直方圖呈現的是三個一起發生的特徵：中心尖峰較高、肩部較薄，而極端尾端較厚；峰度則把這種極端尾端的差異濃縮成一個數字。</p>
<pre><code class="language-r">old_par &lt;- par(
  mfrow = c(1, 2), mar = c(4, 4, 2, 1),
  family = plot_family
)
hist(
  normal_draw, breaks = 80, probability = TRUE,
  xlim = c(-6, 6), col = &quot;#9FC2D4&quot;, border = &quot;white&quot;,
  main = &quot;標準常態&quot;, xlab = &quot;模擬值&quot;
)
curve(dnorm(x), add = TRUE, lwd = 2, col = &quot;#A34045&quot;)
hist(
  t5_draw, breaks = 100, probability = TRUE,
  xlim = c(-6, 6), col = &quot;#D6B0A9&quot;, border = &quot;white&quot;,
  main = &quot;標準化 Student-t(5)&quot;, xlab = &quot;模擬值&quot;
)
curve(dnorm(x), add = TRUE, lwd = 2, col = &quot;#173B57&quot;)
</code></pre>
<p><img alt="相同理論變異數下，標準化 Student-t(5) 的尾端比常態分配厚。" src="./R03_distributions_heavy_tails_files/figure-gfm/simulation-plots-1.png"></p>
<pre><code class="language-r">par(old_par)
</code></pre>
<p>模擬讓我們看懂「相同變異數不代表相同尾端」，卻沒有提供 MSFT 或投資組合的實證結論。接下來才把這套觀察方式帶到固定的歷史資料。</p>
<h2 id="msft">讀取 MSFT 與股票面板<a class="headerlink" href="#msft" title="Permanent link">#</a></h2>
<p>讀入兩份資料後，先依日期排序並確認沒有缺值。<code>R</code> 的每一列是一個共同交易日，每一欄是一檔股票；<code>rowMeans(R)</code> 因此是在同一天對 89 檔股票等權平均，而不是跨時間平均。這個方向若弄反，會得到完全不同的研究對象。</p>
<pre><code class="language-r">msft &lt;- read.csv(project_path(
  &quot;data&quot;, &quot;processed&quot;, &quot;msft_daily_returns_1986_2008.csv&quot;
))
msft$date &lt;- as.Date(msft$date)
# ACF 依賴時間次序，所以在任何診斷前先由早到晚排序。
msft &lt;- msft[order(msft$date), ]

panel &lt;- read.csv(
  project_path(
    &quot;data&quot;, &quot;processed&quot;, &quot;sp500_returns_balanced_2013_2022.csv&quot;
  ),
  check.names = FALSE
)
panel$date &lt;- as.Date(panel$date)
R &lt;- as.matrix(panel[, setdiff(names(panel), &quot;date&quot;)])
storage.mode(R) &lt;- &quot;double&quot;

stopifnot(
  !anyNA(msft$date), !anyNA(msft$simple_return),
  all(diff(msft$date) &gt; 0),
  !anyNA(panel$date), !anyNA(R),
  all(diff(panel$date) &gt; 0)
)

sp_equal &lt;- rowMeans(R)

data_profile &lt;- data.frame(
  序列 = c(&quot;MSFT&quot;, &quot;89 檔股票等權教學投資組合&quot;),
  起日 = c(min(msft$date), min(panel$date)),
  迄日 = c(max(msft$date), max(panel$date)),
  觀察值 = c(nrow(msft), nrow(panel)),
  資產數 = c(1L, ncol(R)),
  單位 = &quot;日簡單報酬，小數&quot;,
  來源 = c(
    &quot;Tsay 教科書網站 d-msft8608.txt&quot;,
    &quot;原課程 S&amp;P 500 價格檔的平衡面板&quot;
  ),
  check.names = FALSE
)
knitr::kable(data_profile)
</code></pre>
<table>
<thead>
<tr>
<th style="text-align: left;">序列</th>
<th style="text-align: left;">起日</th>
<th style="text-align: left;">迄日</th>
<th style="text-align: right;">觀察值</th>
<th style="text-align: right;">資產數</th>
<th style="text-align: left;">單位</th>
<th style="text-align: left;">來源</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align: left;">MSFT</td>
<td style="text-align: left;">1986-03-14</td>
<td style="text-align: left;">2008-12-31</td>
<td style="text-align: right;">5752</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">日簡單報酬，小數</td>
<td style="text-align: left;">Tsay 教科書網站 d-msft8608.txt</td>
</tr>
<tr>
<td style="text-align: left;">89 檔股票等權教學投資組合</td>
<td style="text-align: left;">2013-01-03</td>
<td style="text-align: left;">2022-06-22</td>
<td style="text-align: right;">2384</td>
<td style="text-align: right;">89</td>
<td style="text-align: left;">日簡單報酬，小數</td>
<td style="text-align: left;">原課程 S&amp;P 500 價格檔的平衡面板</td>
</tr>
</tbody>
</table>
<p><code>data_profile</code> 應顯示 MSFT 有 5,752 個交易日，等權組合有 2,384 個共同交易日。兩列的日期範圍不同，因此後面的統計量是在各自樣本內描述，不宜把數值差異全部歸因於資產本身；市場年代、樣本長度與成分股篩選也可能影響結果。</p>
<h2 id="_2">真實報酬的偏態、峰度與尾端<a class="headerlink" href="#_2" title="Permanent link">#</a></h2>
<p>現在用同一組公式整理兩條真實報酬序列。分位數告訴我們左右尾的實際尺度，偏態描述兩側是否對稱，峰度則對極端觀察值特別敏感；三者要放在一起讀，不能只看單一 $p$ 值。</p>
<pre><code class="language-r">empirical_summary &lt;- rbind(
  MSFT = sample_moments(msft$simple_return),
  SP_equal_weight = sample_moments(sp_equal)
)
knitr::kable(round(empirical_summary, 5))
</code></pre>
<table>
<thead>
<tr>
<th style="text-align: left;"></th>
<th style="text-align: right;">n</th>
<th style="text-align: right;">mean</th>
<th style="text-align: right;">sd</th>
<th style="text-align: right;">skewness</th>
<th style="text-align: right;">kurtosis</th>
<th style="text-align: right;">excess_kurtosis</th>
<th style="text-align: right;">q01</th>
<th style="text-align: right;">q05</th>
<th style="text-align: right;">median</th>
<th style="text-align: right;">q95</th>
<th style="text-align: right;">q99</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align: left;">MSFT</td>
<td style="text-align: right;">5752</td>
<td style="text-align: right;">0.00123</td>
<td style="text-align: right;">0.02359</td>
<td style="text-align: right;">-0.13209</td>
<td style="text-align: right;">12.92329</td>
<td style="text-align: right;">9.92329</td>
<td style="text-align: right;">-0.06108</td>
<td style="text-align: right;">-0.03306</td>
<td style="text-align: right;">0.00000</td>
<td style="text-align: right;">0.03846</td>
<td style="text-align: right;">0.06344</td>
</tr>
<tr>
<td style="text-align: left;">SP_equal_weight</td>
<td style="text-align: right;">2384</td>
<td style="text-align: right;">0.00076</td>
<td style="text-align: right;">0.01075</td>
<td style="text-align: right;">-0.67951</td>
<td style="text-align: right;">22.94458</td>
<td style="text-align: right;">19.94458</td>
<td style="text-align: right;">-0.03040</td>
<td style="text-align: right;">-0.01555</td>
<td style="text-align: right;">0.00106</td>
<td style="text-align: right;">0.01469</td>
<td style="text-align: right;">0.02507</td>
</tr>
</tbody>
</table>
<pre><code class="language-r">jb_table &lt;- rbind(
  MSFT = jarque_bera(msft$simple_return),
  SP_equal_weight = jarque_bera(sp_equal)
)
knitr::kable(jb_table, digits = 6)
</code></pre>
<table>
<thead>
<tr>
<th style="text-align: left;"></th>
<th style="text-align: right;">statistic</th>
<th style="text-align: right;">p_value_iid_asymptotic</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align: left;">MSFT</td>
<td style="text-align: right;">23617.11</td>
<td style="text-align: right;">0</td>
</tr>
<tr>
<td style="text-align: left;">SP_equal_weight</td>
<td style="text-align: right;">39696.89</td>
<td style="text-align: right;">0</td>
</tr>
</tbody>
</table>
<p>MSFT 的樣本峰度約為 12.92，等權教學組合約為 22.94，都遠高於常態分配的 3；兩者的 Jarque–Bera 統計量也都很大。就這兩段固定樣本而言，常態分配無法妥善描述偏態與尾端。這項結果只指出常態模型的不足，還沒有在 Student-$t$、偏態 $t$ 或其他厚尾分配之間選出唯一答案。</p>
<p>Jarque–Bera 的卡方近似依賴獨立同分配與有限高階動差。金融報酬常有條件異質變異，因此極小的漸近 $p$ 值適合當作常態模型的警訊，後面仍要檢查報酬與平方報酬的時間相依性。</p>
<h2 id="basicstats-normaltest">套件作法：用 <code>basicStats()</code> 與 <code>normalTest()</code> 整理分配特徵<a class="headerlink" href="#basicstats-normaltest" title="Permanent link">#</a></h2>
<p>原課程的實作程式在
<code>slides/L02_Return_properties/W1L2_R_scripts_Descriptive_stat_returns.R</code>
以 <code>fBasics::basicStats()</code> 整理描述統計，並以
<code>normalTest(..., method = "jb")</code> 執行 Jarque–Bera 檢定。下列程式沿用這個工作流程，但改讀本書的固定資料，不在執行時連線下載。套件會代為計算統計量並整理 <code>fHTEST</code> 輸出；資料期間、報酬尺度、峰度定義與時間相依性是否可忽略，仍要由使用者判斷。</p>
<pre><code class="language-r">stopifnot(requireNamespace(&quot;fBasics&quot;, quietly = TRUE))

empirical_series &lt;- list(
  MSFT = msft$simple_return,
  `S&amp;P 等權教學組合` = sp_equal
)

basic_row &lt;- function(out, row_name) {
  out &lt;- as.matrix(out)
  location &lt;- match(tolower(row_name), tolower(row.names(out)))
  stopifnot(!is.na(location))
  as.numeric(out[location, 1])
}

fbasics_summary &lt;- lapply(empirical_series, fBasics::basicStats)
manual_summary &lt;- lapply(empirical_series, sample_moments)

# 按統計量名稱取值，避免套件輸出列次序改變時配錯數字。
moment_comparison &lt;- do.call(rbind, lapply(names(empirical_series), function(nm) {
  package_result &lt;- as.matrix(fbasics_summary[[nm]])
  manual_result &lt;- manual_summary[[nm]]
  manual_values &lt;- c(
    manual_result[&quot;mean&quot;],
    manual_result[&quot;sd&quot;],
    manual_result[&quot;skewness&quot;],
    manual_result[&quot;excess_kurtosis&quot;]
  )
  package_values &lt;- c(
    basic_row(package_result, &quot;Mean&quot;),
    basic_row(package_result, &quot;Stdev&quot;),
    basic_row(package_result, &quot;Skewness&quot;),
    basic_row(package_result, &quot;Kurtosis&quot;)
  )
  data.frame(
    序列 = nm,
    統計量 = c(&quot;平均數&quot;, &quot;標準差&quot;, &quot;偏態&quot;, &quot;超額峰度&quot;),
    手動版 = unname(manual_values),
    fBasics = package_values,
    套件減手動 = package_values - unname(manual_values),
    check.names = FALSE
  )
}))
row.names(moment_comparison) &lt;- NULL
knitr::kable(moment_comparison, digits = 7)
</code></pre>
<table>
<thead>
<tr>
<th style="text-align: left;">序列</th>
<th style="text-align: left;">統計量</th>
<th style="text-align: right;">手動版</th>
<th style="text-align: right;">fBasics</th>
<th style="text-align: right;">套件減手動</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align: left;">MSFT</td>
<td style="text-align: left;">平均數</td>
<td style="text-align: right;">0.0012318</td>
<td style="text-align: right;">0.001232</td>
<td style="text-align: right;">0.0000002</td>
</tr>
<tr>
<td style="text-align: left;">MSFT</td>
<td style="text-align: left;">標準差</td>
<td style="text-align: right;">0.0235944</td>
<td style="text-align: right;">0.023594</td>
<td style="text-align: right;">-0.0000004</td>
</tr>
<tr>
<td style="text-align: left;">MSFT</td>
<td style="text-align: left;">偏態</td>
<td style="text-align: right;">-0.1320928</td>
<td style="text-align: right;">-0.132058</td>
<td style="text-align: right;">0.0000348</td>
</tr>
<tr>
<td style="text-align: left;">MSFT</td>
<td style="text-align: left;">超額峰度</td>
<td style="text-align: right;">9.9232911</td>
<td style="text-align: right;">9.918798</td>
<td style="text-align: right;">-0.0044931</td>
</tr>
<tr>
<td style="text-align: left;">S&amp;P 等權教學組合</td>
<td style="text-align: left;">平均數</td>
<td style="text-align: right;">0.0007612</td>
<td style="text-align: right;">0.000761</td>
<td style="text-align: right;">-0.0000002</td>
</tr>
<tr>
<td style="text-align: left;">S&amp;P 等權教學組合</td>
<td style="text-align: left;">標準差</td>
<td style="text-align: right;">0.0107466</td>
<td style="text-align: right;">0.010747</td>
<td style="text-align: right;">0.0000004</td>
</tr>
<tr>
<td style="text-align: left;">S&amp;P 等權教學組合</td>
<td style="text-align: left;">偏態</td>
<td style="text-align: right;">-0.6795124</td>
<td style="text-align: right;">-0.679085</td>
<td style="text-align: right;">0.0004274</td>
</tr>
<tr>
<td style="text-align: left;">S&amp;P 等權教學組合</td>
<td style="text-align: left;">超額峰度</td>
<td style="text-align: right;">19.9445772</td>
<td style="text-align: right;">19.925332</td>
<td style="text-align: right;">-0.0192452</td>
</tr>
</tbody>
</table>
<pre><code class="language-r"># 對同一批固定觀察值執行套件版 JB，才能與手動公式比較。
fbasics_jb &lt;- lapply(empirical_series, function(x) {
  fBasics::normalTest(x, method = &quot;jb&quot;)
})

# 先看完整 fHTEST，認識統計量、自由度與 p 值在物件中的位置。
for (nm in names(fbasics_jb)) {
  cat(&quot;\n&quot;, nm, &quot;\n&quot;, sep = &quot;&quot;)
  print(fbasics_jb[[nm]])
}
</code></pre>
<pre><code>## 
## MSFT
## 
## Title:
##  Jarque-Bera Normality Test
## 
## Test Results:
##   STATISTIC:
##     X-squared: 23617.1128
##   P VALUE:
##     Asymptotic p Value: &lt; 2.2e-16 
## 
## 
## S&amp;P 等權教學組合
## 
## Title:
##  Jarque-Bera Normality Test
## 
## Test Results:
##   STATISTIC:
##     X-squared: 39696.8887
##   P VALUE:
##     Asymptotic p Value: &lt; 2.2e-16
</code></pre>
<pre><code class="language-r">extract_fhtest &lt;- function(x) {
  test_result &lt;- methods::slot(x, &quot;test&quot;)
  c(
    statistic = unname(test_result$statistic),
    p_value = unname(test_result$p.value)
  )
}

jb_comparison &lt;- do.call(rbind, lapply(names(empirical_series), function(nm) {
  manual_result &lt;- jarque_bera(empirical_series[[nm]])
  package_result &lt;- extract_fhtest(fbasics_jb[[nm]])
  data.frame(
    序列 = nm,
    手動JB = manual_result[&quot;statistic&quot;],
    fBasics_JB = package_result[&quot;statistic&quot;],
    手動p值 = manual_result[&quot;p_value_iid_asymptotic&quot;],
    fBasics_p值 = package_result[&quot;p_value&quot;],
    check.names = FALSE
  )
}))
row.names(jb_comparison) &lt;- NULL
knitr::kable(jb_comparison, digits = 7)
</code></pre>
<table>
<thead>
<tr>
<th style="text-align: left;">序列</th>
<th style="text-align: right;">手動JB</th>
<th style="text-align: right;">fBasics_JB</th>
<th style="text-align: right;">手動p值</th>
<th style="text-align: right;">fBasics_p值</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align: left;">MSFT</td>
<td style="text-align: right;">23617.11</td>
<td style="text-align: right;">23617.11</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
</tr>
<tr>
<td style="text-align: left;">S&amp;P 等權教學組合</td>
<td style="text-align: right;">39696.89</td>
<td style="text-align: right;">39696.89</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
</tr>
</tbody>
</table>
<p>平均數與標準差先幫我們確認資料與尺度是否一致；偏態、峰度與 Jarque–Bera 數值則可能因有限樣本修正與動差定義不同而略有差異。特別是 <code>basicStats()</code> 的 <code>Kurtosis</code> 採超額峰度，應與上文「常態等於 0」的欄位比較，不能直接對照「常態等於 3」的峰度。表中若出現小幅數值差，先查定義與修正方式；兩種作法在這份固定資料上的方向應一致，都指出常態模型對尾端的描述不足。</p>
<pre><code class="language-r">series_list &lt;- list(
  MSFT = list(date = msft$date, return = msft$simple_return),
  `S&amp;P 等權教學組合` = list(date = panel$date, return = sp_equal)
)

old_par &lt;- par(
  mfrow = c(2, 3), mar = c(4.5, 3.7, 3, 1),
  family = plot_family
)
for (nm in names(series_list)) {
  z &lt;- series_list[[nm]]
  plot(
    z$date, 100 * z$return, type = &quot;l&quot;, col = &quot;#173B57&quot;,
    xlab = &quot;日期&quot;, ylab = &quot;日報酬（%）&quot;, main = nm
  )
  hist(
    z$return, breaks = 70, probability = TRUE,
    col = &quot;#9FC2D4&quot;, border = &quot;white&quot;,
    xlab = &quot;日簡單報酬&quot;, main = paste(nm, &quot;分配&quot;)
  )
  curve(
    dnorm(x, mean(z$return), sd(z$return)),
    add = TRUE, lwd = 2, col = &quot;#A34045&quot;
  )
  qqnorm(
    z$return, pch = 16, cex = 0.4,
    col = &quot;#173B57&quot;, main = paste(nm, &quot;常態 Q–Q&quot;)
  )
  qqline(z$return, col = &quot;#A34045&quot;, lwd = 2)
}
</code></pre>
<p><img alt="MSFT 與等權教學投資組合的時間圖、經驗分配與常態 Q–Q 圖。" src="./R03_distributions_heavy_tails_files/figure-gfm/empirical-plots-1.png"></p>
<pre><code class="language-r">par(old_par)
</code></pre>
<p>時間圖先告訴我們極端波動落在哪些日期，直方圖比較整體形狀，Q–Q 圖則把左右尾偏離常態的方向分開呈現。若尾端點系統性離開參考線，應考慮厚尾創新或更合適的風險衡量方式；圖形本身還不能決定唯一的替代分配。</p>
<h2 id="_3">報酬與平方報酬的時間相依<a class="headerlink" href="#_3" title="Permanent link">#</a></h2>
<p>厚尾描述的是無條件分配，波動群聚則問「大波動之後是否較常接著大波動」。因此同時畫原報酬與平方報酬的自相關函數（ACF）：前者主要看條件平均的線性相依，後者把正負號拿掉，用來觀察波動大小是否具有持續性。</p>
<pre><code class="language-r">old_par &lt;- par(
  mfrow = c(2, 2), mar = c(4, 3.5, 4, 1),
  family = plot_family, cex.main = 0.85
)
for (nm in names(series_list)) {
  z &lt;- series_list[[nm]]$return
  acf(z, lag.max = 30, main = paste(nm, &quot;報酬 ACF&quot;))
  acf(z^2, lag.max = 30, main = paste(nm, &quot;平方報酬 ACF&quot;))
}
</code></pre>
<p><img alt="MSFT 與等權教學投資組合的報酬 ACF 與平方報酬 ACF。" src="./R03_distributions_heavy_tails_files/figure-gfm/acf-diagnostics-1.png"></p>
<pre><code class="language-r">par(old_par)
</code></pre>
<pre><code class="language-r">lb_row &lt;- function(x, series_name) {
  q_return &lt;- Box.test(x, lag = 20, type = &quot;Ljung-Box&quot;)
  q_square &lt;- Box.test(x^2, lag = 20, type = &quot;Ljung-Box&quot;)
  data.frame(
    序列 = series_name,
    Q20_報酬 = unname(q_return$statistic),
    p_報酬 = q_return$p.value,
    Q20_平方報酬 = unname(q_square$statistic),
    p_平方報酬 = q_square$p.value,
    check.names = FALSE
  )
}

diagnostics &lt;- rbind(
  lb_row(msft$simple_return, &quot;MSFT&quot;),
  lb_row(sp_equal, &quot;S&amp;P 等權教學組合&quot;)
)
knitr::kable(diagnostics, digits = 6)
</code></pre>
<table>
<thead>
<tr>
<th style="text-align: left;">序列</th>
<th style="text-align: right;">Q20_報酬</th>
<th style="text-align: right;">p_報酬</th>
<th style="text-align: right;">Q20_平方報酬</th>
<th style="text-align: right;">p_平方報酬</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align: left;">MSFT</td>
<td style="text-align: right;">41.3004</td>
<td style="text-align: right;">0.003408</td>
<td style="text-align: right;">1156.800</td>
<td style="text-align: right;">0</td>
</tr>
<tr>
<td style="text-align: left;">S&amp;P 等權教學組合</td>
<td style="text-align: right;">422.1970</td>
<td style="text-align: right;">0.000000</td>
<td style="text-align: right;">4037.729</td>
<td style="text-align: right;">0</td>
</tr>
</tbody>
</table>
<p>在這份固定資料中，MSFT 報酬的 $Q(20)$ 約為 41.30，等權組合約為 422.20；平方報酬的統計量更分別達約 1,156.80 與 4,037.73。前 20 階同時為零的限制在兩條序列上都遭拒絕，平方報酬的相依尤其明顯。下一步可分開處理兩個問題：條件平均模型檢查殘差是否仍有線性相依，ARCH/GARCH 類模型則處理波動持續性。這些統計量沒有直接證明報酬可交易，也沒有提供造成波動群聚的因果機制。</p>
<h2 id="_4">定位極端日期<a class="headerlink" href="#_4" title="Permanent link">#</a></h2>
<p>由於峰度對少數極端值很敏感，最後把絕對報酬最大的日期列出來。這一步是為了回查資料來源與理解哪些觀察值主導尾端，而不是根據結果大小自動刪除資料。</p>
<pre><code class="language-r">largest_moves &lt;- function(date, x, label, number = 5L) {
  keep &lt;- order(abs(x), decreasing = TRUE)[seq_len(number)]
  data.frame(
    序列 = label,
    日期 = date[keep],
    日簡單報酬 = x[keep],
    check.names = FALSE
  )
}

extreme_table &lt;- rbind(
  largest_moves(msft$date, msft$simple_return, &quot;MSFT&quot;),
  largest_moves(panel$date, sp_equal, &quot;S&amp;P 等權教學組合&quot;)
)
knitr::kable(extreme_table, digits = 6)
</code></pre>
<table>
<thead>
<tr>
<th style="text-align: left;">序列</th>
<th style="text-align: left;">日期</th>
<th style="text-align: right;">日簡單報酬</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align: left;">MSFT</td>
<td style="text-align: left;">1987-10-19</td>
<td style="text-align: right;">-0.301158</td>
</tr>
<tr>
<td style="text-align: left;">MSFT</td>
<td style="text-align: left;">2000-10-19</td>
<td style="text-align: right;">0.195652</td>
</tr>
<tr>
<td style="text-align: left;">MSFT</td>
<td style="text-align: left;">1987-10-26</td>
<td style="text-align: right;">-0.186529</td>
</tr>
<tr>
<td style="text-align: left;">MSFT</td>
<td style="text-align: left;">2008-10-13</td>
<td style="text-align: right;">0.186047</td>
</tr>
<tr>
<td style="text-align: left;">MSFT</td>
<td style="text-align: left;">1987-10-21</td>
<td style="text-align: right;">0.179688</td>
</tr>
<tr>
<td style="text-align: left;">S&amp;P 等權教學組合</td>
<td style="text-align: left;">2020-03-16</td>
<td style="text-align: right;">-0.121581</td>
</tr>
<tr>
<td style="text-align: left;">S&amp;P 等權教學組合</td>
<td style="text-align: left;">2020-03-24</td>
<td style="text-align: right;">0.105691</td>
</tr>
<tr>
<td style="text-align: left;">S&amp;P 等權教學組合</td>
<td style="text-align: left;">2020-03-12</td>
<td style="text-align: right;">-0.096315</td>
</tr>
<tr>
<td style="text-align: left;">S&amp;P 等權教學組合</td>
<td style="text-align: left;">2020-03-13</td>
<td style="text-align: right;">0.087688</td>
</tr>
<tr>
<td style="text-align: left;">S&amp;P 等權教學組合</td>
<td style="text-align: left;">2020-03-09</td>
<td style="text-align: right;">-0.080871</td>
</tr>
</tbody>
</table>
<p>若回查後確認是建檔或價格調整錯誤，應修正資料並重新計算全部統計量；若極端值與原始來源一致，就應保留，因為它們正是厚尾與風險分析要解釋的現象。</p>
<h2 id="_5">這兩段歷史資料給我們的訊息<a class="headerlink" href="#_5" title="Permanent link">#</a></h2>
<p>MSFT 與等權教學組合都呈現高峰度、常態 Q–Q 圖尾端偏離，以及顯著的平方報酬相依。這些證據支持在後續模型中正面處理厚尾與條件異質變異，卻還不能判定哪一個厚尾分配最好，也不能把歷史尾端頻率當成不變的未來機率。實務上的下一步，是在明確的訓練期內比較候選分配與波動模型，再用保留的測試期評估預測分配，而不是只依一次常態性檢定作決定。</p>
      </article>
      <nav class="pager" aria-label="前後附錄"><a rel="prev" href="R02_prices_dates_returns.html">← 價格、日期與報酬率</a><a rel="next" href="R04_ar_ma_arma_simulation.html">AR、MA、ARMA 與真實報酬的 ACF →</a></nav>
      <footer>© 陳釗而　《財務時間序列分析》</footer>
    </main>
    <aside class="page-toc"><h2>本頁目錄</h2><div class="toc">
<ul>
<li><a href="#jarquebera">描述統計與 Jarque–Bera 函數</a></li>
<li><a href="#_1">先用已知分配看懂「厚尾」</a></li>
<li><a href="#msft">讀取 MSFT 與股票面板</a></li>
<li><a href="#_2">真實報酬的偏態、峰度與尾端</a></li>
<li><a href="#basicstats-normaltest">套件作法：用 basicStats() 與 normalTest() 整理分配特徵</a></li>
<li><a href="#_3">報酬與平方報酬的時間相依</a></li>
<li><a href="#_4">定位極端日期</a></li>
<li><a href="#_5">這兩段歷史資料給我們的訊息</a></li>
</ul>
</div>
</aside>
  </div>
</body>
</html>
