<!doctype html>
<html lang="zh-Hant-TW">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="《財務時間序列分析》R 線上附錄：R05：AAPL 的 ARMA 估計、診斷與預測">
  <title>R05：AAPL 的 ARMA 估計、診斷與預測｜財務時間序列分析</title>
  <link rel="stylesheet" href="assets/site.css">
  <script>
    window.MathJax = {
      tex: {inlineMath: [['$', '$'], ['\\(', '\\)']], displayMath: [['$$', '$$'], ['\\[', '\\]']]},
      svg: {fontCache: 'local'},
      options: {skipHtmlTags: ['script', 'noscript', 'style', 'textarea', 'pre', 'code']}
    };
  </script>
  <script defer src="assets/mathjax-loader.js"></script>
  <script defer src="assets/site.js"></script>
</head>
<body>
  <a class="skip-link" href="#main-content">跳到主要內容</a>
  <header class="site-header">
    <button class="menu-button" type="button" aria-controls="site-navigation" aria-expanded="false">目錄</button>
    <a class="brand" href="index.html"><span>財務時間序列分析</span><small>R 線上附錄</small></a>
    <a class="policy-link" href="data-policy.html">資料說明</a>
  </header>
  <div class="layout">
    <nav id="site-navigation" class="sidebar" aria-label="全部線上附錄">
      <p class="sidebar-title">線上附錄</p>
      <ol><li><a href="index.html">首頁</a></li>
<li><a href="data.html">實證資料下載</a></li>
<li><a href="data-policy.html">資料來源與重現說明</a></li>
<li><a href="R00_environment_reproducibility.html">R00　環境、專案與可重現研究</a></li>
<li><a href="R01_r_tidyverse_manual_ols.html">R01　R、tidyverse 與手動 OLS</a></li>
<li><a href="R02_prices_dates_returns.html">R02　價格、日期與報酬率</a></li>
<li><a href="R03_distributions_heavy_tails.html">R03　分配、厚尾與實證特徵</a></li>
<li><a href="R04_ar_ma_arma_simulation.html">R04　AR、MA、ARMA 與真實報酬的 ACF</a></li>
<li><a href="R05_arma_estimation_diagnostics_forecasting.html" aria-current="page" class="active">R05　AAPL 的 ARMA 估計、診斷與預測</a></li>
<li><a href="R06_leak_free_out_of_sample_evaluation.html">R06　TWD／JPY 的無資料洩漏樣本外評估</a></li>
<li><a href="R07_unit_roots_differencing_breaks.html">R07　TWD／JPY 的單根、差分與結構變動</a></li>
<li><a href="R08_arch_garch_asymmetry_forecasting.html">R08　AAPL 的 ARCH、GARCH、非對稱波動與預測</a></li>
<li><a href="R09_portfolio_capm_factors.html">R09　美國十產業投資組合、CAPM 與 Fama–French 三因子</a></li>
<li><a href="R10_pca_factor_analysis.html">R10　真實股票報酬的 PCA、低秩重建與因子分析</a></li>
<li><a href="R11_sp500_pca_corrected.html">R11　S&amp;P 500 平衡子樣本的 PCA 與跨股票落後值修正</a></li>
<li><a href="R12_taiwan_dcc_icapm_case_study.html">R12　臺灣 DCC–ICAPM 的第二階段個案研究</a></li>
<li><a href="R13_regularization.html">R13　Ridge、LASSO、Elastic Net 與 post-LASSO</a></li>
<li><a href="R14_financial_factor_selection.html">R14　機器學習的金融因子選擇</a></li>
<li><a href="R15_double_selection_dml.html">R15　加州學校資料的雙重選擇與 DML 式殘差化</a></li>
<li><a href="R16_var_irf.html">R16　VAR、識別與衝擊反應函數</a></li>
<li><a href="R17_cointegration_vecm.html">R17　共整合、Johansen 檢定與 VECM</a></li>
<li><a href="R18_local_projection_irf.html">R18　VAR、局部投影與進階 IRF</a></li></ol>
    </nav>
    <main id="main-content" class="content">
      <div class="publication-note">
        想自己重算，可以從頁首下載 R Markdown 與執行結果。所有實證例都使用隨書提供的固定資料；
        檔案來源、變數單位與已知限制請見<a href="data-policy.html">資料來源與重現說明</a>。
      </div>
      <article>
        <header class="article-header"><p class="eyebrow">《財務時間序列分析》線上附錄</p><h1>R05：AAPL 的 ARMA 估計、診斷與預測</h1><div class="source-links" aria-label="下載本頁檔案"><a href="source/R05_arma_estimation_diagnostics_forecasting.Rmd">下載 R Markdown</a><a href="source/R05_arma_estimation_diagnostics_forecasting.md">下載執行結果（Markdown）</a></div></header>
        <p>本附錄對應第 6–7 章，要完整走過一次實際的預測流程：只看 AAPL 的早期日對數報酬時，應如何選擇低階 ARMA 模型、檢查根與殘差，並在模型選定後評估未見期間？固定資料源自原課程 S&amp;P 500 價格檔；每一列代表一個交易日，有效報酬樣本為 2019-01-03 至 2022-06-22，共 874 筆，單位是小數日對數報酬。資料建置方式見 <code>data/DATA_SOURCES.md</code>。</p>
<p>第 $t$ 日對數報酬要等當日調整收盤價可得後才能完整計算，所以本頁假設在訓練期最後一日收盤後形成預測。ARMA 模型描述的是 AAPL 報酬的條件平均動態；係數、診斷與預測誤差都沒有識別市場事件的因果效果，也不構成投資建議。</p>
<pre><code class="language-r">knitr::opts_chunk$set(
  echo = TRUE, message = FALSE, warning = FALSE,
  fig.width = 8, fig.height = 4.8,
  dev = &quot;ragg_png&quot;, dpi = 144,
  dev.args = list(background = &quot;white&quot;)
)

root_candidates &lt;- c(&quot;.&quot;, &quot;..&quot;)
is_root &lt;- vapply(root_candidates, function(x) {
  file.exists(file.path(x, &quot;main.tex&quot;))
}, logical(1))
stopifnot(any(is_root))
project_root &lt;- root_candidates[which(is_root)[1]]
project_path &lt;- function(...) file.path(project_root, ...)

stopifnot(
  requireNamespace(&quot;ragg&quot;, quietly = TRUE),
  requireNamespace(&quot;systemfonts&quot;, quietly = TRUE)
)
cwtex_file &lt;- project_path(&quot;assets&quot;, &quot;fonts&quot;, &quot;cwTeXQKai-Medium.ttf&quot;)
stopifnot(file.exists(cwtex_file))
if (!&quot;cwTeX Online&quot; %in% systemfonts::registry_fonts()$family) {
  systemfonts::register_font(&quot;cwTeX Online&quot;, cwtex_file)
}
plot_family &lt;- &quot;cwTeX Online&quot;
</code></pre>
<h2 id="_1">固定資料與時間切分<a class="headerlink" href="#_1" title="Permanent link">#</a></h2>
<p>前 80% 報酬是訓練期，負責比較候選模型、計算 BIC 與估計所有參數；最後 20% 是一次性測試期，只負責回答選定模型在未見資料上的預測誤差。本例沒有另外設驗證期，因為調校工作都限於訓練期內的預先指定候選集合。測試期一旦被拿來改階數或改規格，就不再是未見測試資料。</p>
<pre><code class="language-r">aapl &lt;- read.csv(project_path(
  &quot;data&quot;, &quot;processed&quot;, &quot;aapl_adjusted_daily_2019_2022.csv&quot;
))
aapl$date &lt;- as.Date(aapl$date)
# 報酬的落後關係依日期而定，先排序再切分，不能隨機打散。
aapl &lt;- aapl[order(aapl$date), ]
aapl &lt;- aapl[is.finite(aapl$log_return), ]
row.names(aapl) &lt;- NULL

stopifnot(
  !anyNA(aapl$date), !anyNA(aapl$log_return),
  all(diff(aapl$date) &gt; 0)
)

y &lt;- aapl$log_return
dates &lt;- aapl$date
n &lt;- length(y)
train_end &lt;- floor(0.80 * n)
# 切點只由樣本長度決定，不參考後面的預測分數。
y_train &lt;- y[seq_len(train_end)]
y_test &lt;- y[(train_end + 1L):n]

split_table &lt;- data.frame(
  區段 = c(&quot;訓練期&quot;, &quot;測試期&quot;),
  起日 = dates[c(1L, train_end + 1L)],
  迄日 = dates[c(train_end, n)],
  觀察值 = c(train_end, n - train_end),
  資料來源 = &quot;原課程 S&amp;P 500 價格檔的 AAPL 固定版本&quot;,
  單位 = &quot;日對數報酬，小數&quot;,
  check.names = FALSE
)
knitr::kable(split_table)
</code></pre>
<table>
<thead>
<tr>
<th style="text-align: left;">區段</th>
<th style="text-align: left;">起日</th>
<th style="text-align: left;">迄日</th>
<th style="text-align: right;">觀察值</th>
<th style="text-align: left;">資料來源</th>
<th style="text-align: left;">單位</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align: left;">訓練期</td>
<td style="text-align: left;">2019-01-03</td>
<td style="text-align: left;">2021-10-11</td>
<td style="text-align: right;">699</td>
<td style="text-align: left;">原課程 S&amp;P 500 價格檔的 AAPL 固定版本</td>
<td style="text-align: left;">日對數報酬，小數</td>
</tr>
<tr>
<td style="text-align: left;">測試期</td>
<td style="text-align: left;">2021-10-12</td>
<td style="text-align: left;">2022-06-22</td>
<td style="text-align: right;">175</td>
<td style="text-align: left;">原課程 S&amp;P 500 價格檔的 AAPL 固定版本</td>
<td style="text-align: left;">日對數報酬，小數</td>
</tr>
</tbody>
</table>
<p>表中訓練期為 2019-01-03 至 2021-10-11，共 699 筆；測試期為 2021-10-12 至 2022-06-22，共 175 筆。這裡評估的是「在 2021-10-11 收盤後一次形成，之後不重新估計」的多步預測。若希望每個交易日都加入新資訊並重新估計，應改用 R06 的擴展或滾動起點設計。</p>
<h2 id="_2">只在訓練期比較低階候選模型<a class="headerlink" href="#_2" title="Permanent link">#</a></h2>
<p>候選集合在讀取測試結果以前固定，只包含 $p,q\leq 2$ 的幾個低階模型。每個模型都用相同的 699 筆訓練資料與最大概似法估計，才可以公平比較 BIC。要注意，<code>stats::arima()</code> 對定態 ARMA 所報的 <code>intercept</code> 是序列平均數，而不是
$Y_t=c+\phi Y_{t-1}+a_t$ 中的 $c$。</p>
<pre><code class="language-r">candidate_orders &lt;- list(
  ARMA00 = c(0, 0, 0),
  AR10 = c(1, 0, 0),
  MA01 = c(0, 0, 1),
  ARMA11 = c(1, 0, 1),
  AR20 = c(2, 0, 0),
  MA02 = c(0, 0, 2),
  ARMA21 = c(2, 0, 1),
  ARMA12 = c(1, 0, 2)
)

# 對每一個事前列出的階數，用同一估計法配適同一訓練期。
fits &lt;- lapply(candidate_orders, function(ord) {
  arima(
    y_train,
    order = ord,
    include.mean = TRUE,
    method = &quot;ML&quot;
  )
})
stopifnot(all(vapply(fits, function(z) z$code == 0, logical(1))))

model_table &lt;- data.frame(
  模型 = names(fits),
  p = vapply(candidate_orders, function(z) z[1], numeric(1)),
  q = vapply(candidate_orders, function(z) z[3], numeric(1)),
  對數概似 = vapply(fits, function(z) as.numeric(logLik(z)), numeric(1)),
  AIC = vapply(fits, AIC, numeric(1)),
  BIC = vapply(fits, BIC, numeric(1)),
  check.names = FALSE
)
model_table &lt;- model_table[order(model_table$BIC), ]
row.names(model_table) &lt;- NULL
knitr::kable(model_table, digits = 3)
</code></pre>
<table>
<thead>
<tr>
<th style="text-align: left;">模型</th>
<th style="text-align: right;">p</th>
<th style="text-align: right;">q</th>
<th style="text-align: right;">對數概似</th>
<th style="text-align: right;">AIC</th>
<th style="text-align: right;">BIC</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align: left;">AR10</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1692.238</td>
<td style="text-align: right;">-3378.477</td>
<td style="text-align: right;">-3364.828</td>
</tr>
<tr>
<td style="text-align: left;">MA01</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1691.150</td>
<td style="text-align: right;">-3376.300</td>
<td style="text-align: right;">-3362.651</td>
</tr>
<tr>
<td style="text-align: left;">ARMA11</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1692.452</td>
<td style="text-align: right;">-3376.904</td>
<td style="text-align: right;">-3358.705</td>
</tr>
<tr>
<td style="text-align: left;">AR20</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1692.444</td>
<td style="text-align: right;">-3376.887</td>
<td style="text-align: right;">-3358.689</td>
</tr>
<tr>
<td style="text-align: left;">MA02</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">1692.226</td>
<td style="text-align: right;">-3376.451</td>
<td style="text-align: right;">-3358.253</td>
</tr>
<tr>
<td style="text-align: left;">ARMA12</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">1692.452</td>
<td style="text-align: right;">-3374.905</td>
<td style="text-align: right;">-3352.156</td>
</tr>
<tr>
<td style="text-align: left;">ARMA21</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1692.452</td>
<td style="text-align: right;">-3374.903</td>
<td style="text-align: right;">-3352.155</td>
</tr>
<tr>
<td style="text-align: left;">ARMA00</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1678.042</td>
<td style="text-align: right;">-3352.084</td>
<td style="text-align: right;">-3342.985</td>
</tr>
</tbody>
</table>
<pre><code class="language-r">selected_name &lt;- model_table$模型[1]
selected_fit &lt;- fits[[selected_name]]
selected_order &lt;- candidate_orders[[selected_name]]
selected_name
</code></pre>
<pre><code>## [1] &quot;AR10&quot;
</code></pre>
<p>表格由 BIC 小到大排列，這份訓練資料選出 AR(1)。BIC 只是在既定候選集合中的訓練期相對比較，不是測試期成績，也沒有保證候選集合包含真實資料生成過程。若所有候選模型的殘差都不理想，仍應降低結論強度或重新設計候選集合。</p>
<h2 id="autoarima">套件作法：用 <code>auto.arima()</code> 比較候選階數<a class="headerlink" href="#autoarima" title="Permanent link">#</a></h2>
<p>原課程的
<code>slides/L04_ARMA/W1L4_R_template_for_estimating_ARMA.R</code>
以 <code>forecast::auto.arima()</code> 選階、<code>checkresiduals()</code> 診斷，再以
<code>forecast()</code> 形成預測。
<code>slides/L05_Forecasting_and_CV/W1L5_R_prediction_cv.R</code>
另示範了不使用逐步搜尋的 AIC 選階。下列兩個套件版本都只讀訓練期：第一個把階數範圍與資訊準則限制成上一節的八種 $(p,d,q)$ 組合，但 <code>auto.arima()</code> 另會容許零平均規格，因此模型候選集合仍比手動版稍廣；第二個沿用原課程較自動的 AIC 搜尋。若要和手動版使用完全相同的候選集合，應逐一對 <code>candidate_orders</code> 呼叫 <code>forecast::Arima(..., include.mean = TRUE, method = "ML")</code>，再比較 BIC。<code>auto.arima()</code> 會代為估計與排序候選模型，卻不會替我們決定測試期何時開始、該採 AIC 或 BIC，或哪些階數具有實質上的合理性。</p>
<pre><code class="language-r">stopifnot(requireNamespace(&quot;forecast&quot;, quietly = TRUE))

# 階數範圍與手動版相同；auto.arima() 另會比較零平均規格。
fit_auto_matched &lt;- forecast::auto.arima(
  y_train,
  d = 0,
  stationary = TRUE,
  seasonal = FALSE,
  max.p = 2,
  max.q = 2,
  max.order = 3,
  ic = &quot;bic&quot;,
  stepwise = FALSE,
  approximation = FALSE,
  allowmean = TRUE
)

# 再沿用原課程 AIC 搜尋；階數仍只由訓練期決定。
fit_auto_course &lt;- forecast::auto.arima(
  y_train,
  seasonal = FALSE,
  ic = &quot;aic&quot;,
  stepwise = FALSE,
  approximation = FALSE
)

order_text &lt;- function(fit) {
  order &lt;- forecast::arimaorder(fit)[c(&quot;p&quot;, &quot;d&quot;, &quot;q&quot;)]
  sprintf(&quot;ARIMA(%d,%d,%d)&quot;, order[&quot;p&quot;], order[&quot;d&quot;], order[&quot;q&quot;])
}

selection_comparison &lt;- data.frame(
  方法 = c(
    &quot;手動候選集／BIC&quot;,
    &quot;forecast 同階數範圍／BIC&quot;,
    &quot;forecast 原課程搜尋／AIC&quot;
  ),
  選定模型 = c(
    sprintf(
      &quot;ARIMA(%d,%d,%d)&quot;,
      selected_order[1], selected_order[2], selected_order[3]
    ),
    order_text(fit_auto_matched),
    order_text(fit_auto_course)
  ),
  對數概似 = c(
    as.numeric(logLik(selected_fit)),
    as.numeric(logLik(fit_auto_matched)),
    as.numeric(logLik(fit_auto_course))
  ),
  AIC = c(
    AIC(selected_fit), AIC(fit_auto_matched), AIC(fit_auto_course)
  ),
  BIC = c(
    BIC(selected_fit), BIC(fit_auto_matched), BIC(fit_auto_course)
  ),
  check.names = FALSE
)
knitr::kable(selection_comparison, digits = 3)
</code></pre>
<table>
<thead>
<tr>
<th style="text-align: left;">方法</th>
<th style="text-align: left;">選定模型</th>
<th style="text-align: right;">對數概似</th>
<th style="text-align: right;">AIC</th>
<th style="text-align: right;">BIC</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align: left;">手動候選集／BIC</td>
<td style="text-align: left;">ARIMA(1,0,0)</td>
<td style="text-align: right;">1692.238</td>
<td style="text-align: right;">-3378.477</td>
<td style="text-align: right;">-3364.828</td>
</tr>
<tr>
<td style="text-align: left;">forecast 同階數範圍／BIC</td>
<td style="text-align: left;">ARIMA(1,0,0)</td>
<td style="text-align: right;">1692.238</td>
<td style="text-align: right;">-3378.477</td>
<td style="text-align: right;">-3364.828</td>
</tr>
<tr>
<td style="text-align: left;">forecast 原課程搜尋／AIC</td>
<td style="text-align: left;">ARIMA(2,0,3)</td>
<td style="text-align: right;">1708.172</td>
<td style="text-align: right;">-3402.344</td>
<td style="text-align: right;">-3370.497</td>
</tr>
</tbody>
</table>
<p>同階數範圍搜尋與手動表若選到相同結果，只能說兩者在這份資料上的相對勝者一致；由於前者另容許零平均，不能據此宣稱候選集合完全相同。若兩者結果不同，應先檢查平均數規格；若要逐模型核對，則應使用前述 <code>forecast::Arima()</code> 寫法固定每個階數與 <code>include.mean = TRUE</code>。原課程 AIC 版本的搜尋範圍與懲罰也不同，選到另一個階數時，差異來自研究設定而非套件失靈。報告「自動選階」結果時，仍要一併寫清楚資訊準則、搜尋範圍、平均數規格與訓練期間。</p>
<h2 id="_3">係數、定態根與可逆根<a class="headerlink" href="#_3" title="Permanent link">#</a></h2>
<p>選定階數後，先讀係數的方向與不確定性，再檢查 AR 與 MA 多項式的根。係數表的每一列是一個參數，<code>估計值</code> 與 <code>標準誤</code> 使用日對數報酬的小數尺度；根表則列出複數根的實部、虛部與模。</p>
<pre><code class="language-r">coefficient_table &lt;- data.frame(
  參數 = names(coef(selected_fit)),
  估計值 = as.numeric(coef(selected_fit)),
  標準誤 = sqrt(diag(selected_fit$var.coef)),
  check.names = FALSE
)
knitr::kable(coefficient_table, digits = 6)
</code></pre>
<table>
<thead>
<tr>
<th style="text-align: left;"></th>
<th style="text-align: left;">參數</th>
<th style="text-align: right;">估計值</th>
<th style="text-align: right;">標準誤</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align: left;">ar1</td>
<td style="text-align: left;">ar1</td>
<td style="text-align: right;">-0.202870</td>
<td style="text-align: right;">0.037686</td>
</tr>
<tr>
<td style="text-align: left;">intercept</td>
<td style="text-align: left;">intercept</td>
<td style="text-align: right;">0.001906</td>
<td style="text-align: right;">0.000677</td>
</tr>
</tbody>
</table>
<pre><code class="language-r">extract_roots &lt;- function(fit) {
  b &lt;- coef(fit)
  ar_coef &lt;- b[grep(&quot;^ar[0-9]+$&quot;, names(b))]
  ma_coef &lt;- b[grep(&quot;^ma[0-9]+$&quot;, names(b))]

  # AR 與 MA 多項式的符號不同，分開建立可避免根的方向寫反。
  ar_roots &lt;- if (length(ar_coef)) {
    polyroot(c(1, -ar_coef))
  } else {
    complex()
  }
  ma_roots &lt;- if (length(ma_coef)) {
    polyroot(c(1, ma_coef))
  } else {
    complex()
  }

  rbind(
    if (length(ar_roots)) data.frame(
      部分 = &quot;AR&quot;, 實部 = Re(ar_roots), 虛部 = Im(ar_roots), 模 = Mod(ar_roots)
    ),
    if (length(ma_roots)) data.frame(
      部分 = &quot;MA&quot;, 實部 = Re(ma_roots), 虛部 = Im(ma_roots), 模 = Mod(ma_roots)
    )
  )
}

root_table &lt;- extract_roots(selected_fit)
if (nrow(root_table)) {
  knitr::kable(root_table, digits = 5)
  stopifnot(all(root_table$模 &gt; 1))
} else {
  cat(&quot;所選模型沒有 AR 或 MA 根需要檢查。\n&quot;)
}
</code></pre>
<p>所選 AR(1) 的 AR 係數約為 -0.2029，標準誤約為 0.0377；<code>intercept</code> 約為 0.001906，這裡代表訓練期估計的序列平均數。負的 AR 係數表示報酬偏離平均數後，下一日的條件平均有短期反向調整，但它只是樣本內的縮減式動態，不能解讀成可交易策略或因果反應。</p>
<p>AR 根在單位圓外時，估計模型具有因果定態表示；若模型含 MA 項，MA 根在單位圓外則表示可逆。根通過條件是採用模型的必要檢查，還不是充分診斷；根接近 1 時，有限樣本推論與遠期預測仍可能不穩定。</p>
<h2 id="_4">訓練期殘差診斷<a class="headerlink" href="#_4" title="Permanent link">#</a></h2>
<p>資訊準則選出相對勝者後，要問的是它是否已把可預測的平均動態留在殘差之外。第一列 Ljung–Box 檢查殘差前 20 階的線性相依，並扣除已估的 AR 與 MA 參數自由度；第二列檢查平方殘差，尋找尚未處理的波動群聚。</p>
<pre><code class="language-r">selected_residual &lt;- as.numeric(residuals(selected_fit))
selected_residual &lt;- selected_residual[is.finite(selected_residual)]
p_plus_q &lt;- selected_order[1] + selected_order[3]

# 平均方程的檢定扣除 p+q；平方殘差列用來診斷波動，不沿用同一 fitdf。
q_mean &lt;- Box.test(
  selected_residual, lag = 20, type = &quot;Ljung-Box&quot;,
  fitdf = p_plus_q
)
q_square &lt;- Box.test(
  selected_residual^2, lag = 20, type = &quot;Ljung-Box&quot;
)

diagnostic_table &lt;- data.frame(
  檢查對象 = c(&quot;殘差&quot;, &quot;平方殘差&quot;),
  Q20 = c(unname(q_mean$statistic), unname(q_square$statistic)),
  自由度 = c(unname(q_mean$parameter), unname(q_square$parameter)),
  p值 = c(q_mean$p.value, q_square$p.value),
  check.names = FALSE
)
knitr::kable(diagnostic_table, digits = 6)
</code></pre>
<table>
<thead>
<tr>
<th style="text-align: left;">檢查對象</th>
<th style="text-align: right;">Q20</th>
<th style="text-align: right;">自由度</th>
<th style="text-align: right;">p值</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align: left;">殘差</td>
<td style="text-align: right;">54.18846</td>
<td style="text-align: right;">19</td>
<td style="text-align: right;">3.1e-05</td>
</tr>
<tr>
<td style="text-align: left;">平方殘差</td>
<td style="text-align: right;">355.02037</td>
<td style="text-align: right;">20</td>
<td style="text-align: right;">0.0e+00</td>
</tr>
</tbody>
</table>
<p>本次 AR(1) 殘差的 Ljung–Box $p$ 值約為 $3.1\times10^{-5}$，平方殘差的 $p$ 值更接近零。這是明確的診斷警訊：BIC 所選模型只是候選集合內的相對勝者，並未清除全部平均與波動相依。平均殘差的結果提示可以檢查其他低階規格；平方殘差則提示把 ARCH/GARCH 類模型納入後續分析。</p>
<pre><code class="language-r">matched_order &lt;- forecast::arimaorder(fit_auto_matched)[c(&quot;p&quot;, &quot;d&quot;, &quot;q&quot;)]
matched_residual &lt;- as.numeric(residuals(fit_auto_matched))
matched_residual &lt;- matched_residual[is.finite(matched_residual)]
matched_df &lt;- matched_order[&quot;p&quot;] + matched_order[&quot;q&quot;]

matched_q_mean &lt;- Box.test(
  matched_residual,
  lag = 20,
  type = &quot;Ljung-Box&quot;,
  fitdf = matched_df
)
matched_q_square &lt;- Box.test(
  matched_residual^2,
  lag = 20,
  type = &quot;Ljung-Box&quot;
)

diagnostic_comparison &lt;- data.frame(
  方法 = rep(c(&quot;手動候選集&quot;, &quot;forecast 同階數範圍搜尋&quot;), each = 2),
  檢查對象 = rep(c(&quot;殘差&quot;, &quot;平方殘差&quot;), 2),
  Q20 = c(
    unname(q_mean$statistic), unname(q_square$statistic),
    unname(matched_q_mean$statistic),
    unname(matched_q_square$statistic)
  ),
  p值 = c(
    q_mean$p.value, q_square$p.value,
    matched_q_mean$p.value, matched_q_square$p.value
  ),
  check.names = FALSE
)
knitr::kable(diagnostic_comparison, digits = 7)
</code></pre>
<table>
<thead>
<tr>
<th style="text-align: left;">方法</th>
<th style="text-align: left;">檢查對象</th>
<th style="text-align: right;">Q20</th>
<th style="text-align: right;">p值</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align: left;">手動候選集</td>
<td style="text-align: left;">殘差</td>
<td style="text-align: right;">54.18846</td>
<td style="text-align: right;">3.09e-05</td>
</tr>
<tr>
<td style="text-align: left;">手動候選集</td>
<td style="text-align: left;">平方殘差</td>
<td style="text-align: right;">355.02037</td>
<td style="text-align: right;">0.00e+00</td>
</tr>
<tr>
<td style="text-align: left;">forecast 同階數範圍搜尋</td>
<td style="text-align: left;">殘差</td>
<td style="text-align: right;">54.19123</td>
<td style="text-align: right;">3.09e-05</td>
</tr>
<tr>
<td style="text-align: left;">forecast 同階數範圍搜尋</td>
<td style="text-align: left;">平方殘差</td>
<td style="text-align: right;">355.02619</td>
<td style="text-align: right;">0.00e+00</td>
</tr>
</tbody>
</table>
<pre><code class="language-r"># 原課程使用的一行診斷，同時呈現殘差路徑、ACF 與聯合檢定。
forecast::checkresiduals(fit_auto_matched, lag = 20)
</code></pre>
<p><img alt="forecast::checkresiduals() 對同階數範圍 BIC 自動選階模型的殘差診斷。" src="./R05_arma_estimation_diagnostics_forecasting_files/figure-gfm/course-auto-arima-diagnostics-1.png"></p>
<pre><code>## 
##  Ljung-Box test
## 
## data:  Residuals from ARIMA(1,0,0) with non-zero mean
## Q* = 54.191, df = 19, p-value = 3.089e-05
## 
## Model df: 1.   Total lags used: 20
</code></pre>
<p>若同階數範圍搜尋與手動程式不只選到相同階數，也採用相同的平均數規格，上表的兩組診斷才應幾乎重合。小數點差異可能來自初始化與數值容差；若模型階數、平均數規格或自由度不同，就要先統一這些設定、估計法與 <code>fitdf</code>，才能把 Ljung–Box 數值放在同一基準上比較。<code>checkresiduals()</code> 替我們排好圖與檢定，仍需由讀者根據殘差或平方殘差的警訊決定下一步。</p>
<pre><code class="language-r">old_par &lt;- par(
  mfrow = c(1, 3), mar = c(4.5, 3.5, 4, 1),
  family = plot_family, cex.main = 0.88
)
plot(
  dates[seq_along(selected_residual)], 100 * selected_residual,
  type = &quot;l&quot;, col = &quot;#173B57&quot;,
  xlab = &quot;日期&quot;, ylab = &quot;殘差（%）&quot;, main = selected_name
)
acf(selected_residual, lag.max = 30, main = &quot;殘差 ACF&quot;)
acf(selected_residual^2, lag.max = 30, main = &quot;平方殘差 ACF&quot;)
</code></pre>
<p><img alt="BIC 所選模型的訓練期殘差、殘差 ACF 與平方殘差 ACF。" src="./R05_arma_estimation_diagnostics_forecasting_files/figure-gfm/diagnostics-plots-1.png"></p>
<pre><code class="language-r">par(old_par)
</code></pre>
<p>圖形補上檢定數字沒有呈現的資訊：殘差時間圖可以看出警訊集中在哪些日期，兩張 ACF 則顯示相依落在何種期距。由於殘差仍有線性相依，所選低階平均數模型只能視為候選集合中的相對勝者；平方殘差的明顯相依則是第 11–12 章 ARCH/GARCH 模型的直接動機。</p>
<h2 id="_5">選定模型後的一次多步預測<a class="headerlink" href="#_5" title="Permanent link">#</a></h2>
<p>現在才讓模型面對保留的 175 筆測試資料。<code>predict()</code> 在訓練期末使用已估的 AR(1) 係數，一次產生整段多步預測；測試期內即使已經觀察到新的實際報酬，也不把它加入模型。這個設計回答「若在 2021-10-11 只估計一次，遠期預測會如何」，與每日更新的一步預測是不同問題。</p>
<pre><code class="language-r">h &lt;- length(y_test)
# 模型、參數與預測起點都在讀取測試答案前選定。
forecast_object &lt;- predict(selected_fit, n.ahead = h)

forecast_table &lt;- data.frame(
  日期 = dates[(train_end + 1L):n],
  實際值 = y_test,
  ARMA預測 = as.numeric(forecast_object$pred),
  預測標準誤 = as.numeric(forecast_object$se),
  check.names = FALSE
)
forecast_table$下界95 &lt;- forecast_table$ARMA預測 -
  1.96 * forecast_table$預測標準誤
forecast_table$上界95 &lt;- forecast_table$ARMA預測 +
  1.96 * forecast_table$預測標準誤
forecast_table$ARMA誤差 &lt;- forecast_table$實際值 -
  forecast_table$ARMA預測

knitr::kable(head(forecast_table, 8), digits = 6)
</code></pre>
<table>
<thead>
<tr>
<th style="text-align: left;">日期</th>
<th style="text-align: right;">實際值</th>
<th style="text-align: right;">ARMA預測</th>
<th style="text-align: right;">預測標準誤</th>
<th style="text-align: right;">下界95</th>
<th style="text-align: right;">上界95</th>
<th style="text-align: right;">ARMA誤差</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align: left;">2021-10-12</td>
<td style="text-align: right;">-0.009145</td>
<td style="text-align: right;">0.002420</td>
<td style="text-align: right;">0.021496</td>
<td style="text-align: right;">-0.039711</td>
<td style="text-align: right;">0.044552</td>
<td style="text-align: right;">-0.011565</td>
</tr>
<tr>
<td style="text-align: left;">2021-10-13</td>
<td style="text-align: right;">-0.004249</td>
<td style="text-align: right;">0.001802</td>
<td style="text-align: right;">0.021933</td>
<td style="text-align: right;">-0.041188</td>
<td style="text-align: right;">0.044791</td>
<td style="text-align: right;">-0.006051</td>
</tr>
<tr>
<td style="text-align: left;">2021-10-14</td>
<td style="text-align: right;">0.020024</td>
<td style="text-align: right;">0.001927</td>
<td style="text-align: right;">0.021951</td>
<td style="text-align: right;">-0.041097</td>
<td style="text-align: right;">0.044952</td>
<td style="text-align: right;">0.018097</td>
</tr>
<tr>
<td style="text-align: left;">2021-10-15</td>
<td style="text-align: right;">0.007485</td>
<td style="text-align: right;">0.001902</td>
<td style="text-align: right;">0.021952</td>
<td style="text-align: right;">-0.041124</td>
<td style="text-align: right;">0.044928</td>
<td style="text-align: right;">0.005583</td>
</tr>
<tr>
<td style="text-align: left;">2021-10-18</td>
<td style="text-align: right;">0.011737</td>
<td style="text-align: right;">0.001907</td>
<td style="text-align: right;">0.021952</td>
<td style="text-align: right;">-0.041119</td>
<td style="text-align: right;">0.044933</td>
<td style="text-align: right;">0.009830</td>
</tr>
<tr>
<td style="text-align: left;">2021-10-19</td>
<td style="text-align: right;">0.014968</td>
<td style="text-align: right;">0.001906</td>
<td style="text-align: right;">0.021952</td>
<td style="text-align: right;">-0.041120</td>
<td style="text-align: right;">0.044932</td>
<td style="text-align: right;">0.013062</td>
</tr>
<tr>
<td style="text-align: left;">2021-10-20</td>
<td style="text-align: right;">0.003356</td>
<td style="text-align: right;">0.001906</td>
<td style="text-align: right;">0.021952</td>
<td style="text-align: right;">-0.041120</td>
<td style="text-align: right;">0.044932</td>
<td style="text-align: right;">0.001450</td>
</tr>
<tr>
<td style="text-align: left;">2021-10-21</td>
<td style="text-align: right;">0.001473</td>
<td style="text-align: right;">0.001906</td>
<td style="text-align: right;">0.021952</td>
<td style="text-align: right;">-0.041120</td>
<td style="text-align: right;">0.044932</td>
<td style="text-align: right;">-0.000433</td>
</tr>
</tbody>
</table>
<p>表中每一列是一個測試交易日：<code>ARMA預測</code> 是訓練期末可形成的條件平均預測，<code>預測標準誤</code> 隨期距反映未來創新累積，<code>實際值</code> 只在事後計分時使用。任何一列的實際值都沒有回流到後面日期的預測。</p>
<pre><code class="language-r">score_row &lt;- function(actual, forecast, label) {
  error &lt;- actual - forecast
  data.frame(
    模型 = label,
    RMSE = sqrt(mean(error^2)),
    MAE = mean(abs(error)),
    平均誤差 = mean(error),
    check.names = FALSE
  )
}

score_table &lt;- rbind(
  score_row(y_test, forecast_table$ARMA預測, selected_name),
  score_row(y_test, rep(0, h), &quot;零報酬&quot;),
  score_row(y_test, rep(mean(y_train), h), &quot;訓練期平均數&quot;)
)
score_table$常態區間涵蓋率 &lt;- c(
  mean(
    y_test &gt;= forecast_table$下界95 &amp;
      y_test &lt;= forecast_table$上界95
  ),
  NA_real_, NA_real_
)
knitr::kable(score_table, digits = 6)
</code></pre>
<table>
<thead>
<tr>
<th style="text-align: left;">模型</th>
<th style="text-align: right;">RMSE</th>
<th style="text-align: right;">MAE</th>
<th style="text-align: right;">平均誤差</th>
<th style="text-align: right;">常態區間涵蓋率</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align: left;">AR10</td>
<td style="text-align: right;">0.020809</td>
<td style="text-align: right;">0.016036</td>
<td style="text-align: right;">-0.002191</td>
<td style="text-align: right;">0.977143</td>
</tr>
<tr>
<td style="text-align: left;">零報酬</td>
<td style="text-align: right;">0.020694</td>
<td style="text-align: right;">0.015951</td>
<td style="text-align: right;">-0.000283</td>
<td style="text-align: right;">NA</td>
</tr>
<tr>
<td style="text-align: left;">訓練期平均數</td>
<td style="text-align: right;">0.020805</td>
<td style="text-align: right;">0.016031</td>
<td style="text-align: right;">-0.002162</td>
<td style="text-align: right;">NA</td>
</tr>
</tbody>
</table>
<p>RMSE 對較大的預測錯誤給予更高權重，MAE 則以絕對誤差計分，平均誤差用來觀察預測是否整體偏高或偏低。在這 175 筆固定測試資料中，零報酬基準的 RMSE 與 MAE 都略低於訓練期 BIC 所選的 AR(1)。這個結果很有教學價值：樣本內資訊準則較佳，不保證樣本外預測勝過簡單基準。既然測試答案已經看過，就不應再為了追上零報酬基準而回頭改階數。</p>
<h2 id="forecast-accuracy">套件作法：用 <code>forecast()</code> 形成預測並以 <code>accuracy()</code> 計分<a class="headerlink" href="#forecast-accuracy" title="Permanent link">#</a></h2>
<p>下列程式對前面兩個 <code>auto.arima()</code> 模型執行原課程採用的
<code>forecast()</code> 與 <code>accuracy()</code> 工作流程。<code>forecast()</code> 會整理點預測與區間，<code>accuracy()</code> 會依實際值計算常用誤差指標；兩者都不會替我們維持樣本外紀律。因此，兩個模型的階數仍在訓練期選定，測試期只用來計分。</p>
<pre><code class="language-r">course_forecast_matched &lt;- forecast::forecast(
  fit_auto_matched,
  h = h,
  level = 95
)
course_forecast_aic &lt;- forecast::forecast(
  fit_auto_course,
  h = h,
  level = 95
)

accuracy_row &lt;- function(object, actual, label) {
  # accuracy() 可能同時回報訓練與測試列；此處明確取最後一列測試結果。
  package_accuracy &lt;- forecast::accuracy(object, actual)
  test_accuracy &lt;- package_accuracy[nrow(package_accuracy), , drop = FALSE]
  data.frame(
    模型 = label,
    RMSE = unname(test_accuracy[1, &quot;RMSE&quot;]),
    MAE = unname(test_accuracy[1, &quot;MAE&quot;]),
    平均誤差 = unname(test_accuracy[1, &quot;ME&quot;]),
    常態區間涵蓋率 = mean(
      actual &gt;= as.numeric(object$lower[, 1]) &amp;
        actual &lt;= as.numeric(object$upper[, 1])
    ),
    check.names = FALSE
  )
}

manual_accuracy &lt;- score_row(
  y_test,
  forecast_table$ARMA預測,
  paste0(&quot;手動候選：&quot;, selected_name)
)
manual_accuracy$常態區間涵蓋率 &lt;- mean(
  y_test &gt;= forecast_table$下界95 &amp;
    y_test &lt;= forecast_table$上界95
)

zero_accuracy &lt;- score_row(y_test, rep(0, h), &quot;零報酬&quot;)
zero_accuracy$常態區間涵蓋率 &lt;- NA_real_

package_forecast_comparison &lt;- rbind(
  manual_accuracy,
  accuracy_row(
    course_forecast_matched,
    y_test,
    paste0(&quot;forecast 同階數範圍BIC：&quot;, order_text(fit_auto_matched))
  ),
  accuracy_row(
    course_forecast_aic,
    y_test,
    paste0(&quot;forecast 原課程AIC：&quot;, order_text(fit_auto_course))
  ),
  zero_accuracy
)
row.names(package_forecast_comparison) &lt;- NULL
knitr::kable(package_forecast_comparison, digits = 7)
</code></pre>
<table>
<thead>
<tr>
<th style="text-align: left;">模型</th>
<th style="text-align: right;">RMSE</th>
<th style="text-align: right;">MAE</th>
<th style="text-align: right;">平均誤差</th>
<th style="text-align: right;">常態區間涵蓋率</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align: left;">手動候選：AR10</td>
<td style="text-align: right;">0.0208091</td>
<td style="text-align: right;">0.0160361</td>
<td style="text-align: right;">-0.0021910</td>
<td style="text-align: right;">0.9771429</td>
</tr>
<tr>
<td style="text-align: left;">forecast 同階數範圍BIC：ARIMA(1,0,0)</td>
<td style="text-align: right;">0.0208091</td>
<td style="text-align: right;">0.0160361</td>
<td style="text-align: right;">-0.0021907</td>
<td style="text-align: right;">0.9771429</td>
</tr>
<tr>
<td style="text-align: left;">forecast 原課程AIC：ARIMA(2,0,3)</td>
<td style="text-align: right;">0.0208093</td>
<td style="text-align: right;">0.0160548</td>
<td style="text-align: right;">-0.0022301</td>
<td style="text-align: right;">0.9771429</td>
</tr>
<tr>
<td style="text-align: left;">零報酬</td>
<td style="text-align: right;">0.0206943</td>
<td style="text-align: right;">0.0159514</td>
<td style="text-align: right;">-0.0002826</td>
<td style="text-align: right;">NA</td>
</tr>
</tbody>
</table>
<p>若手動 BIC 與同階數範圍的 <code>auto.arima()</code> 不只選到同一階數，也採用相同平均數規格，兩者點預測與評分才應幾乎相同。只看階數相同，還不足以宣稱兩套程式估的是同一個模型。原課程 AIC 版本可能選到不同階數，因而產生不同預測。比較表要連同模型標籤一起讀，不能只挑 RMSE 最小的一列，事後把它說成事前選定的模型。</p>
<pre><code class="language-r">old_par &lt;- par(family = plot_family)
plot(
  forecast_table$日期, 100 * forecast_table$實際值,
  type = &quot;l&quot;, col = &quot;gray35&quot;,
  xlab = &quot;日期&quot;, ylab = &quot;日對數報酬（%）&quot;
)
polygon(
  c(forecast_table$日期, rev(forecast_table$日期)),
  100 * c(forecast_table$下界95, rev(forecast_table$上界95)),
  border = NA, col = adjustcolor(&quot;#9FC2D4&quot;, alpha.f = 0.45)
)
lines(
  forecast_table$日期, 100 * forecast_table$ARMA預測,
  col = &quot;#A34045&quot;, lwd = 2
)
lines(
  forecast_table$日期, 100 * forecast_table$實際值,
  col = &quot;gray35&quot;
)
legend(
  &quot;topright&quot;, c(&quot;實際值&quot;, &quot;ARMA 點預測&quot;, &quot;95% 區間&quot;),
  col = c(&quot;gray35&quot;, &quot;#A34045&quot;, &quot;#9FC2D4&quot;),
  lty = c(1, 1, NA), pch = c(NA, NA, 15), bty = &quot;n&quot;
)
</code></pre>
<p><img alt="訓練期末一次形成的 AAPL 多步預測與 95% 常態近似區間。" src="./R05_arma_estimation_diagnostics_forecasting_files/figure-gfm/forecast-plot-1.png"></p>
<pre><code class="language-r">par(old_par)
</code></pre>
<p>圖中帶狀區域是以所選 ARMA 模型與常態近似形成的 95% 區間，主要反映未來創新的不確定性。它沒有完整納入參數估計、階數選擇、厚尾與條件異質變異造成的不確定性。表中的固定測試期涵蓋率只能描述這 175 筆觀察值；若涵蓋不足，下一步應檢查創新分配與波動模型，而不是任意加寬區間到看起來理想。</p>
<h2 id="_6">用已知真值確認符號與估計流程<a class="headerlink" href="#_6" title="Permanent link">#</a></h2>
<p>最後另生成一條 5,000 期的 ARMA(1,1) 模擬序列。因為 AR 與 MA 真值已知，我們可以確認 <code>arima()</code> 的係數符號與名稱是否和課文一致。這條模擬序列只檢查程式流程，不參與 AAPL 的模型選擇、預測評分或實證結論。</p>
<pre><code class="language-r">set.seed(20260721)
truth &lt;- c(ar1 = 0.55, ma1 = -0.35)
simulated_check &lt;- as.numeric(arima.sim(
  model = list(ar = truth[&quot;ar1&quot;], ma = truth[&quot;ma1&quot;]),
  n = 5000, sd = 0.01
))
fit_check &lt;- arima(
  simulated_check, order = c(1, 0, 1),
  include.mean = TRUE, method = &quot;ML&quot;
)
check_table &lt;- data.frame(
  參數 = names(truth),
  真值 = truth,
  估計值 = coef(fit_check)[names(truth)],
  check.names = FALSE
)
knitr::kable(check_table, digits = 4)
</code></pre>
<table>
<thead>
<tr>
<th style="text-align: left;"></th>
<th style="text-align: left;">參數</th>
<th style="text-align: right;">真值</th>
<th style="text-align: right;">估計值</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align: left;">ar1</td>
<td style="text-align: left;">ar1</td>
<td style="text-align: right;">0.55</td>
<td style="text-align: right;">0.5673</td>
</tr>
<tr>
<td style="text-align: left;">ma1</td>
<td style="text-align: left;">ma1</td>
<td style="text-align: right;">-0.35</td>
<td style="text-align: right;">-0.3769</td>
</tr>
</tbody>
</table>
<pre><code class="language-r">stopifnot(max(abs(check_table$估計值 - check_table$真值)) &lt; 0.10)
</code></pre>
<p>兩個估計值與真值的差距都應小於事前設定的 0.10 容許範圍。若沒有通過，應先檢查 MA 符號慣例、係數名稱與模擬長度，而不能據此修改 AAPL 的實證模型。</p>
<h2 id="_7">如何延伸這次結果<a class="headerlink" href="#_7" title="Permanent link">#</a></h2>
<p>這份 AAPL 固定樣本顯示，訓練期 BIC 在既定候選集合中選出 AR(1)，但殘差與平方殘差仍有明顯相依，而且一次形成的多步預測沒有勝過零報酬基準。可以得到的結論是：這個低階條件平均模型尚不足以完整描述資料，也沒有展現穩健的樣本外優勢；我們還不能把負 AR 係數解讀成可交易規律。</p>
<p>下一步可在新的訓練／驗證設計中納入其他平均規格與 ARCH/GARCH 波動模型，再保留另一段未見期間評估。報告時應保存固定資料版本、訓練截止日、候選集合、估計方法、截距參數化、資訊準則、根、殘差診斷、預測期距與區間假設。若看過這 175 筆測試結果後再換模型，這段期間就只能當作驗證資料；新的主張需要另一段真正未見的測試期。</p>
      </article>
      <nav class="pager" aria-label="前後附錄"><a rel="prev" href="R04_ar_ma_arma_simulation.html">← AR、MA、ARMA 與真實報酬的 ACF</a><a rel="next" href="R06_leak_free_out_of_sample_evaluation.html">TWD／JPY 的無資料洩漏樣本外評估 →</a></nav>
      <footer>© 陳釗而　《財務時間序列分析》</footer>
    </main>
    <aside class="page-toc"><h2>本頁目錄</h2><div class="toc">
<ul>
<li><a href="#_1">固定資料與時間切分</a></li>
<li><a href="#_2">只在訓練期比較低階候選模型</a></li>
<li><a href="#autoarima">套件作法：用 auto.arima() 比較候選階數</a></li>
<li><a href="#_3">係數、定態根與可逆根</a></li>
<li><a href="#_4">訓練期殘差診斷</a></li>
<li><a href="#_5">選定模型後的一次多步預測</a></li>
<li><a href="#forecast-accuracy">套件作法：用 forecast() 形成預測並以 accuracy() 計分</a></li>
<li><a href="#_6">用已知真值確認符號與估計流程</a></li>
<li><a href="#_7">如何延伸這次結果</a></li>
</ul>
</div>
</aside>
  </div>
</body>
</html>
