<!doctype html>
<html lang="zh-Hant-TW">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="《財務時間序列分析》R 線上附錄：R06：TWD／JPY 的無資料洩漏樣本外評估">
  <title>R06：TWD／JPY 的無資料洩漏樣本外評估｜財務時間序列分析</title>
  <link rel="stylesheet" href="assets/site.css">
  <script>
    window.MathJax = {
      tex: {inlineMath: [['$', '$'], ['\\(', '\\)']], displayMath: [['$$', '$$'], ['\\[', '\\]']]},
      svg: {fontCache: 'local'},
      options: {skipHtmlTags: ['script', 'noscript', 'style', 'textarea', 'pre', 'code']}
    };
  </script>
  <script defer src="assets/mathjax-loader.js"></script>
  <script defer src="assets/site.js"></script>
</head>
<body>
  <a class="skip-link" href="#main-content">跳到主要內容</a>
  <header class="site-header">
    <button class="menu-button" type="button" aria-controls="site-navigation" aria-expanded="false">目錄</button>
    <a class="brand" href="index.html"><span>財務時間序列分析</span><small>R 線上附錄</small></a>
    <a class="policy-link" href="data-policy.html">資料說明</a>
  </header>
  <div class="layout">
    <nav id="site-navigation" class="sidebar" aria-label="全部線上附錄">
      <p class="sidebar-title">線上附錄</p>
      <ol><li><a href="index.html">首頁</a></li>
<li><a href="data.html">實證資料下載</a></li>
<li><a href="data-policy.html">資料來源與重現說明</a></li>
<li><a href="R00_environment_reproducibility.html">R00　環境、專案與可重現研究</a></li>
<li><a href="R01_r_tidyverse_manual_ols.html">R01　R、tidyverse 與手動 OLS</a></li>
<li><a href="R02_prices_dates_returns.html">R02　價格、日期與報酬率</a></li>
<li><a href="R03_distributions_heavy_tails.html">R03　分配、厚尾與實證特徵</a></li>
<li><a href="R04_ar_ma_arma_simulation.html">R04　AR、MA、ARMA 與真實報酬的 ACF</a></li>
<li><a href="R05_arma_estimation_diagnostics_forecasting.html">R05　AAPL 的 ARMA 估計、診斷與預測</a></li>
<li><a href="R06_leak_free_out_of_sample_evaluation.html" aria-current="page" class="active">R06　TWD／JPY 的無資料洩漏樣本外評估</a></li>
<li><a href="R07_unit_roots_differencing_breaks.html">R07　TWD／JPY 的單根、差分與結構變動</a></li>
<li><a href="R08_arch_garch_asymmetry_forecasting.html">R08　AAPL 的 ARCH、GARCH、非對稱波動與預測</a></li>
<li><a href="R09_portfolio_capm_factors.html">R09　美國十產業投資組合、CAPM 與 Fama–French 三因子</a></li>
<li><a href="R10_pca_factor_analysis.html">R10　真實股票報酬的 PCA、低秩重建與因子分析</a></li>
<li><a href="R11_sp500_pca_corrected.html">R11　S&amp;P 500 平衡子樣本的 PCA 與跨股票落後值修正</a></li>
<li><a href="R12_taiwan_dcc_icapm_case_study.html">R12　臺灣 DCC–ICAPM 的第二階段個案研究</a></li>
<li><a href="R13_regularization.html">R13　Ridge、LASSO、Elastic Net 與 post-LASSO</a></li>
<li><a href="R14_financial_factor_selection.html">R14　機器學習的金融因子選擇</a></li>
<li><a href="R15_double_selection_dml.html">R15　加州學校資料的雙重選擇與 DML 式殘差化</a></li>
<li><a href="R16_var_irf.html">R16　VAR、識別與衝擊反應函數</a></li>
<li><a href="R17_cointegration_vecm.html">R17　共整合、Johansen 檢定與 VECM</a></li>
<li><a href="R18_local_projection_irf.html">R18　VAR、局部投影與進階 IRF</a></li></ol>
    </nav>
    <main id="main-content" class="content">
      <div class="publication-note">
        想自己重算，可以從頁首下載 R Markdown 與執行結果。所有實證例都使用隨書提供的固定資料；
        檔案來源、變數單位與已知限制請見<a href="data-policy.html">資料來源與重現說明</a>。
      </div>
      <article>
        <header class="article-header"><p class="eyebrow">《財務時間序列分析》線上附錄</p><h1>R06：TWD／JPY 的無資料洩漏樣本外評估</h1><div class="source-links" aria-label="下載本頁檔案"><a href="source/R06_leak_free_out_of_sample_evaluation.Rmd">下載 R Markdown</a><a href="source/R06_leak_free_out_of_sample_evaluation.md">下載執行結果（Markdown）</a></div></header>
        <p>本附錄對應第 8 章，專門回答樣本外評估最容易出錯的一個問題：在每個預測起點，我們是否真的只使用當時已知的資料？例子以 FRED 的 JPY/USD（<code>DEXJPUS</code>）與 TWD/USD（<code>DEXTAUS</code>）建構交叉匯率，逐日起點預測下一個有效共同觀察日的 TWD/JPY 對數報酬。</p>
<p><code>twd_per_jpy</code> 表示「1 日圓值多少新臺幣」，報酬欄位是小數日對數報酬；0.01 代表約 1%。合併後的固定檔涵蓋 2020-01-02 至 2022-12-16，每一列是一個 FRED 觀察日期，建置與缺值規則見 <code>data/DATA_SOURCES.md</code>。本頁把資料中的觀察日期視為可用日期；若要即時部署，還要另行核對兩條 FRED 序列實際發布的時間與修訂版本，不能假設觀察值在當日任何時點都已可取得。</p>
<p>下列比較只描述固定樣本中的預測誤差。模型沒有使用利率、政策或其他結構變數，因此結果不具有因果解讀，也不構成可交易績效的宣稱。</p>
<pre><code class="language-r">knitr::opts_chunk$set(
  echo = TRUE, message = FALSE, warning = FALSE,
  fig.width = 8, fig.height = 5,
  dev = &quot;ragg_png&quot;, dpi = 144,
  dev.args = list(background = &quot;white&quot;)
)

root_candidates &lt;- c(&quot;.&quot;, &quot;..&quot;)
is_root &lt;- vapply(root_candidates, function(x) {
  file.exists(file.path(x, &quot;main.tex&quot;))
}, logical(1))
stopifnot(any(is_root))
project_root &lt;- root_candidates[which(is_root)[1]]
project_path &lt;- function(...) file.path(project_root, ...)

stopifnot(
  requireNamespace(&quot;ragg&quot;, quietly = TRUE),
  requireNamespace(&quot;systemfonts&quot;, quietly = TRUE)
)
cwtex_file &lt;- project_path(&quot;assets&quot;, &quot;fonts&quot;, &quot;cwTeXQKai-Medium.ttf&quot;)
stopifnot(file.exists(cwtex_file))
if (!&quot;cwTeX Online&quot; %in% systemfonts::registry_fonts()$family) {
  systemfonts::register_font(&quot;cwTeX Online&quot;, cwtex_file)
}
plot_family &lt;- &quot;cwTeX Online&quot;
</code></pre>
<h2 id="_1">固定資料與預測目標<a class="headerlink" href="#_1" title="Permanent link">#</a></h2>
<p>FRED 兩市場的休市日不完全相同，所以合併檔的個別匯率欄會出現缺值。本附錄只保留預先計算且為有限值的 <code>log_return_twd_per_jpy</code>，沒有用未來值回填休市日。這樣一來，預測目標 $y_{t+1}$ 指的是「下一個兩條匯率都能形成有效交叉匯率報酬的觀察日」，不一定是下一個日曆日。</p>
<pre><code class="language-r">fx &lt;- read.csv(project_path(
  &quot;data&quot;, &quot;processed&quot;, &quot;fred_jpy_twd_daily_2020_2022.csv&quot;
))
fx$date &lt;- as.Date(fx$date)
# 先按觀察日期排序，後面的起點與目標索引才具有時間意義。
fx &lt;- fx[order(fx$date), ]

required &lt;- c(
  &quot;date&quot;, &quot;jpy_per_usd&quot;, &quot;twd_per_usd&quot;,
  &quot;twd_per_jpy&quot;, &quot;log_return_twd_per_jpy&quot;
)
stopifnot(all(required %in% names(fx)), all(diff(fx$date) &gt; 0))

missing_table &lt;- data.frame(
  欄位 = required[-1],
  缺值數 = colSums(is.na(fx[required[-1]])),
  check.names = FALSE
)
knitr::kable(missing_table)
</code></pre>
<table>
<thead>
<tr>
<th style="text-align: left;"></th>
<th style="text-align: left;">欄位</th>
<th style="text-align: right;">缺值數</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align: left;">jpy_per_usd</td>
<td style="text-align: left;">jpy_per_usd</td>
<td style="text-align: right;">32</td>
</tr>
<tr>
<td style="text-align: left;">twd_per_usd</td>
<td style="text-align: left;">twd_per_usd</td>
<td style="text-align: right;">32</td>
</tr>
<tr>
<td style="text-align: left;">twd_per_jpy</td>
<td style="text-align: left;">twd_per_jpy</td>
<td style="text-align: right;">32</td>
</tr>
<tr>
<td style="text-align: left;">log_return_twd_per_jpy</td>
<td style="text-align: left;">log_return_twd_per_jpy</td>
<td style="text-align: right;">63</td>
</tr>
</tbody>
</table>
<pre><code class="language-r">usable &lt;- fx[is.finite(fx$log_return_twd_per_jpy), ]
y &lt;- usable$log_return_twd_per_jpy
dates &lt;- usable$date
n &lt;- length(y)

stopifnot(!anyNA(y), all(diff(dates) &gt; 0))

data_profile &lt;- data.frame(
  序列 = &quot;TWD per JPY 交叉匯率對數報酬&quot;,
  起日 = min(dates),
  迄日 = max(dates),
  有效報酬數 = n,
  單位 = &quot;小數日對數報酬&quot;,
  原始來源 = &quot;FRED DEXJPUS 與 DEXTAUS&quot;,
  check.names = FALSE
)
knitr::kable(data_profile)
</code></pre>
<table>
<thead>
<tr>
<th style="text-align: left;">序列</th>
<th style="text-align: left;">起日</th>
<th style="text-align: left;">迄日</th>
<th style="text-align: right;">有效報酬數</th>
<th style="text-align: left;">單位</th>
<th style="text-align: left;">原始來源</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align: left;">TWD per JPY 交叉匯率對數報酬</td>
<td style="text-align: left;">2020-01-03</td>
<td style="text-align: left;">2022-12-16</td>
<td style="text-align: right;">709</td>
<td style="text-align: left;">小數日對數報酬</td>
<td style="text-align: left;">FRED DEXJPUS 與 DEXTAUS</td>
</tr>
</tbody>
</table>
<p>缺值表先呈現原始合併檔各欄的缺值數，讓讀者知道最後樣本為何少於檔案列數。篩選後共有 709 筆有效日對數報酬，期間為 2020-01-03 至 2022-12-16。這 709 筆才是下列切分與預測的觀察單位；若更改缺值或跨市場對齊規則，所有切點與評分都要重新計算。</p>
<h2 id="_2">依時間固定訓練、驗證與測試期<a class="headerlink" href="#_2" title="Permanent link">#</a></h2>
<p>前 60% 是初始訓練期，用來提供每個候選模型的第一段歷史資料；接下來 20% 是驗證期，只用來比較滾動視窗與模型；最後 20% 是測試期，負責評估已選定的規格。金融時間序列不能隨機打散，否則未來觀察值會混入早期模型的估計與調校。</p>
<pre><code class="language-r">train_end &lt;- floor(0.60 * n)
validation_end &lt;- floor(0.80 * n)

# 切點只依事前比例決定，不參考任何模型的驗證或測試分數。
split_table &lt;- data.frame(
  區段 = c(&quot;訓練期&quot;, &quot;驗證期&quot;, &quot;測試期&quot;),
  起始索引 = c(1L, train_end + 1L, validation_end + 1L),
  結束索引 = c(train_end, validation_end, n),
  check.names = FALSE
)
split_table$起日 &lt;- dates[split_table$起始索引]
split_table$迄日 &lt;- dates[split_table$結束索引]
split_table$觀察值 &lt;- with(
  split_table, 結束索引 - 起始索引 + 1L
)
knitr::kable(split_table)
</code></pre>
<table>
<thead>
<tr>
<th style="text-align: left;">區段</th>
<th style="text-align: right;">起始索引</th>
<th style="text-align: right;">結束索引</th>
<th style="text-align: left;">起日</th>
<th style="text-align: left;">迄日</th>
<th style="text-align: right;">觀察值</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align: left;">訓練期</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">425</td>
<td style="text-align: left;">2020-01-03</td>
<td style="text-align: left;">2021-10-06</td>
<td style="text-align: right;">425</td>
</tr>
<tr>
<td style="text-align: left;">驗證期</td>
<td style="text-align: right;">426</td>
<td style="text-align: right;">567</td>
<td style="text-align: left;">2021-10-07</td>
<td style="text-align: left;">2022-05-12</td>
<td style="text-align: right;">142</td>
</tr>
<tr>
<td style="text-align: left;">測試期</td>
<td style="text-align: right;">568</td>
<td style="text-align: right;">709</td>
<td style="text-align: left;">2022-05-13</td>
<td style="text-align: left;">2022-12-16</td>
<td style="text-align: right;">142</td>
</tr>
</tbody>
</table>
<p>表中訓練期有 425 筆，從 2020-01-03 到 2021-10-06；驗證期有 142 筆，從 2021-10-07 到 2022-05-12；測試期也有 142 筆，從 2022-05-13 到 2022-12-16。在任一預測起點 $t$，程式只能使用截至第 $t$ 筆已知報酬，並預測尚未觀察的第 $t+1$ 筆。</p>
<h2 id="_3">單一起點的預測函數<a class="headerlink" href="#_3" title="Permanent link">#</a></h2>
<p>先把「某一個起點可以看到什麼」寫成函數，再把函數套到許多起點。輸入包括完整報酬向量、目前起點、模型名稱與滾動視窗；輸出則明列訓練起點、訓練終點、目標索引、預測與事後實際值。把這些索引留在結果中，稍後才能逐列檢查資訊時序。</p>
<pre><code class="language-r">forecast_at_origin &lt;- function(y, origin, model, window = NA_integer_) {
  # 目標固定為 origin + 1；任何模型分支都不得讀取這一筆來估計。
  stopifnot(origin &gt;= 3L, origin &lt; length(y))

  if (model == &quot;zero&quot;) {
    training_start &lt;- 1L
    prediction &lt;- 0
  } else if (model == &quot;expanding_mean&quot;) {
    training_start &lt;- 1L
    prediction &lt;- mean(y[training_start:origin])
  } else if (model == &quot;rolling_mean&quot;) {
    stopifnot(is.finite(window), origin &gt;= window)
    # 滾動視窗只保留當時最近的 window 筆，較舊資訊在此規格中不再使用。
    training_start &lt;- origin - window + 1L
    prediction &lt;- mean(y[training_start:origin])
  } else if (model == &quot;expanding_ar1&quot;) {
    training_start &lt;- 1L
    z &lt;- y[training_start:origin]
    # AR(1) 的每一列用 z_{s-1} 解釋 z_s；最後一筆 y[origin] 只進入預測式。
    beta &lt;- qr.solve(cbind(1, z[-length(z)]), z[-1])
    prediction &lt;- beta[1] + beta[2] * y[origin]
  } else if (model == &quot;rolling_ar1&quot;) {
    stopifnot(is.finite(window), origin &gt;= window)
    training_start &lt;- origin - window + 1L
    z &lt;- y[training_start:origin]
    beta &lt;- qr.solve(cbind(1, z[-length(z)]), z[-1])
    prediction &lt;- beta[1] + beta[2] * y[origin]
  } else {
    stop(&quot;未知模型。&quot;)
  }

  data.frame(
    origin = origin,
    target_index = origin + 1L,
    training_start = training_start,
    training_end = origin,
    forecast = as.numeric(prediction),
    # actual 只隨輸出帶回供事後計分，不進入上方任何估計步驟。
    actual = y[origin + 1L]
  )
}

evaluate_origins &lt;- function(y, origins, model, window = NA_integer_) {
  # 每個起點獨立重估，模擬真實時間向前走時可取得的資訊。
  out &lt;- do.call(rbind, lapply(origins, function(origin) {
    forecast_at_origin(y, origin, model, window)
  }))
  out$model &lt;- model
  out$window &lt;- window
  out$error &lt;- out$actual - out$forecast
  out$model_label &lt;- if (is.finite(window)) {
    paste0(model, &quot;_&quot;, window)
  } else {
    model
  }
  stopifnot(
    # 這兩項條件是資料時序的最低要求：訓練結束於起點，且早於目標。
    all(out$training_end == out$origin),
    all(out$training_end &lt; out$target_index)
  )
  out
}
</code></pre>
<h2 id="_4">驗證期選擇滾動規格<a class="headerlink" href="#_4" title="Permanent link">#</a></h2>
<p>候選規格包括 20、60、120、250 個有效觀察值的滾動平均，以及 60、120、250 期的滾動 AR(1)。所有視窗都在讀取測試期以前列出；每個驗證目標只用其起點以前的資料形成一步預測。視窗與模型按驗證期 RMSE 選一次，MAE 則協助觀察排序是否對極端誤差敏感。</p>
<pre><code class="language-r">validation_origins &lt;- train_end:(validation_end - 1L)
candidate_specs &lt;- rbind(
  data.frame(model = &quot;rolling_mean&quot;, window = c(20L, 60L, 120L, 250L)),
  data.frame(model = &quot;rolling_ar1&quot;, window = c(60L, 120L, 250L))
)

validation_results &lt;- lapply(seq_len(nrow(candidate_specs)), function(i) {
  evaluate_origins(
    y, validation_origins,
    model = candidate_specs$model[i],
    window = candidate_specs$window[i]
  )
})

# 對每個候選規格使用完全相同的驗證目標日期，分數才可比較。
validation_score &lt;- do.call(rbind, lapply(seq_len(nrow(candidate_specs)), function(i) {
  z &lt;- validation_results[[i]]
  data.frame(
    模型 = candidate_specs$model[i],
    視窗 = candidate_specs$window[i],
    RMSE = sqrt(mean(z$error^2)),
    MAE = mean(abs(z$error)),
    check.names = FALSE
  )
}))
validation_score &lt;- validation_score[order(validation_score$RMSE), ]
row.names(validation_score) &lt;- NULL
knitr::kable(validation_score, digits = 7)
</code></pre>
<table>
<thead>
<tr>
<th style="text-align: left;">模型</th>
<th style="text-align: right;">視窗</th>
<th style="text-align: right;">RMSE</th>
<th style="text-align: right;">MAE</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align: left;">rolling_ar1</td>
<td style="text-align: right;">250</td>
<td style="text-align: right;">0.0048233</td>
<td style="text-align: right;">0.0036531</td>
</tr>
<tr>
<td style="text-align: left;">rolling_ar1</td>
<td style="text-align: right;">120</td>
<td style="text-align: right;">0.0048261</td>
<td style="text-align: right;">0.0036490</td>
</tr>
<tr>
<td style="text-align: left;">rolling_mean</td>
<td style="text-align: right;">250</td>
<td style="text-align: right;">0.0048415</td>
<td style="text-align: right;">0.0036668</td>
</tr>
<tr>
<td style="text-align: left;">rolling_mean</td>
<td style="text-align: right;">120</td>
<td style="text-align: right;">0.0048465</td>
<td style="text-align: right;">0.0036683</td>
</tr>
<tr>
<td style="text-align: left;">rolling_ar1</td>
<td style="text-align: right;">60</td>
<td style="text-align: right;">0.0048830</td>
<td style="text-align: right;">0.0037129</td>
</tr>
<tr>
<td style="text-align: left;">rolling_mean</td>
<td style="text-align: right;">60</td>
<td style="text-align: right;">0.0049024</td>
<td style="text-align: right;">0.0037357</td>
</tr>
<tr>
<td style="text-align: left;">rolling_mean</td>
<td style="text-align: right;">20</td>
<td style="text-align: right;">0.0049426</td>
<td style="text-align: right;">0.0037453</td>
</tr>
</tbody>
</table>
<pre><code class="language-r">selected_model &lt;- validation_score$模型[1]
selected_window &lt;- validation_score$視窗[1]
c(selected_model = selected_model, selected_window = selected_window)
</code></pre>
<pre><code>##  selected_model selected_window 
##   &quot;rolling_ar1&quot;           &quot;250&quot;
</code></pre>
<p>這份驗證資料選出 250 期滾動 AR(1)。它表示在既定候選集合中，較長視窗的 AR(1) 驗證期 RMSE 最低；這不是 250 期視窗在所有時期都最佳的證明。選定後，模型與視窗不再因測試期結果調整。</p>
<h2 id="_5">選定規格後的一次性測試<a class="headerlink" href="#_5" title="Permanent link">#</a></h2>
<p>測試期比較零報酬、擴展平均、擴展 AR(1) 與驗證期選出的滾動規格。每一個起點都用當時已經觀察到的歷史資料重新估計。當某一日的實際報酬公布後，它可以進入下一個起點的訓練視窗；但在預測該日本身時，這個實際值仍完全不可見。這正是逐日起點的一步預測設計。</p>
<pre><code class="language-r">test_origins &lt;- validation_end:(n - 1L)

# 所有模型使用相同起點與目標日，差異只來自預測規則。
test_results &lt;- rbind(
  evaluate_origins(y, test_origins, &quot;zero&quot;),
  evaluate_origins(y, test_origins, &quot;expanding_mean&quot;),
  evaluate_origins(y, test_origins, &quot;expanding_ar1&quot;),
  evaluate_origins(
    y, test_origins, selected_model, window = selected_window
  )
)

test_results$origin_date &lt;- dates[test_results$origin]
test_results$target_date &lt;- dates[test_results$target_index]
test_results$training_start_date &lt;- dates[test_results$training_start]
test_results$training_end_date &lt;- dates[test_results$training_end]

knitr::kable(head(test_results[c(
  &quot;model_label&quot;, &quot;origin_date&quot;, &quot;target_date&quot;,
  &quot;training_start_date&quot;, &quot;training_end_date&quot;,
  &quot;forecast&quot;, &quot;actual&quot;
)], 8), digits = 7)
</code></pre>
<table>
<thead>
<tr>
<th style="text-align: left;">model_label</th>
<th style="text-align: left;">origin_date</th>
<th style="text-align: left;">target_date</th>
<th style="text-align: left;">training_start_date</th>
<th style="text-align: left;">training_end_date</th>
<th style="text-align: right;">forecast</th>
<th style="text-align: right;">actual</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align: left;">zero</td>
<td style="text-align: left;">2022-05-12</td>
<td style="text-align: left;">2022-05-13</td>
<td style="text-align: left;">2020-01-03</td>
<td style="text-align: left;">2022-05-12</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">-0.0104596</td>
</tr>
<tr>
<td style="text-align: left;">zero</td>
<td style="text-align: left;">2022-05-13</td>
<td style="text-align: left;">2022-05-16</td>
<td style="text-align: left;">2020-01-03</td>
<td style="text-align: left;">2022-05-13</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">-0.0000523</td>
</tr>
<tr>
<td style="text-align: left;">zero</td>
<td style="text-align: left;">2022-05-16</td>
<td style="text-align: left;">2022-05-17</td>
<td style="text-align: left;">2020-01-03</td>
<td style="text-align: left;">2022-05-16</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">-0.0046028</td>
</tr>
<tr>
<td style="text-align: left;">zero</td>
<td style="text-align: left;">2022-05-17</td>
<td style="text-align: left;">2022-05-18</td>
<td style="text-align: left;">2020-01-03</td>
<td style="text-align: left;">2022-05-17</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0.0108216</td>
</tr>
<tr>
<td style="text-align: left;">zero</td>
<td style="text-align: left;">2022-05-18</td>
<td style="text-align: left;">2022-05-19</td>
<td style="text-align: left;">2020-01-03</td>
<td style="text-align: left;">2022-05-18</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0.0053627</td>
</tr>
<tr>
<td style="text-align: left;">zero</td>
<td style="text-align: left;">2022-05-19</td>
<td style="text-align: left;">2022-05-20</td>
<td style="text-align: left;">2020-01-03</td>
<td style="text-align: left;">2022-05-19</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">-0.0069319</td>
</tr>
<tr>
<td style="text-align: left;">zero</td>
<td style="text-align: left;">2022-05-20</td>
<td style="text-align: left;">2022-05-23</td>
<td style="text-align: left;">2020-01-03</td>
<td style="text-align: left;">2022-05-20</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0.0002881</td>
</tr>
<tr>
<td style="text-align: left;">zero</td>
<td style="text-align: left;">2022-05-23</td>
<td style="text-align: left;">2022-05-24</td>
<td style="text-align: left;">2020-01-03</td>
<td style="text-align: left;">2022-05-23</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0.0092556</td>
</tr>
</tbody>
</table>
<p>輸出把每一筆測試預測的資訊範圍攤開：<code>training_end_date</code> 應等於 <code>origin_date</code>，而且早於 <code>target_date</code>。滾動模型的 <code>training_start_date</code> 會隨起點向前移動；擴展模型則持續保留最初觀察值。</p>
<pre><code class="language-r">score_one &lt;- function(z) {
  data.frame(
    模型 = z$model_label[1],
    觀察值 = nrow(z),
    RMSE = sqrt(mean(z$error^2)),
    MAE = mean(abs(z$error)),
    平均誤差 = mean(z$error),
    check.names = FALSE
  )
}

score_table &lt;- do.call(
  rbind,
  lapply(split(test_results, test_results$model_label), score_one)
)
score_table &lt;- score_table[order(score_table$RMSE), ]
row.names(score_table) &lt;- NULL
knitr::kable(score_table, digits = 7)
</code></pre>
<table>
<thead>
<tr>
<th style="text-align: left;">模型</th>
<th style="text-align: right;">觀察值</th>
<th style="text-align: right;">RMSE</th>
<th style="text-align: right;">MAE</th>
<th style="text-align: right;">平均誤差</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align: left;">rolling_ar1_250</td>
<td style="text-align: right;">142</td>
<td style="text-align: right;">0.0081441</td>
<td style="text-align: right;">0.0060522</td>
<td style="text-align: right;">0.0005755</td>
</tr>
<tr>
<td style="text-align: left;">expanding_ar1</td>
<td style="text-align: right;">142</td>
<td style="text-align: right;">0.0082058</td>
<td style="text-align: right;">0.0061228</td>
<td style="text-align: right;">0.0004600</td>
</tr>
<tr>
<td style="text-align: left;">zero</td>
<td style="text-align: right;">142</td>
<td style="text-align: right;">0.0083126</td>
<td style="text-align: right;">0.0062443</td>
<td style="text-align: right;">0.0001272</td>
</tr>
<tr>
<td style="text-align: left;">expanding_mean</td>
<td style="text-align: right;">142</td>
<td style="text-align: right;">0.0083264</td>
<td style="text-align: right;">0.0062311</td>
<td style="text-align: right;">0.0004108</td>
</tr>
</tbody>
</table>
<p>RMSE 會放大少數大誤差的影響，MAE 對每筆絕對誤差給相同權重，平均誤差則檢查整體高估或低估。142 筆測試預測中，250 期滾動 AR(1) 的 RMSE 為 0.0081441，低於零報酬基準的 0.0083126；差距約為 0.00017 個小數報酬單位，幅度不大。</p>
<p>這些分數只描述 2022-05-13 至 2022-12-16 的固定測試期，而且該段期間出現較高波動。可以說驗證期選出的規格在這一段略勝零報酬基準，還不能推論長期排序、統計顯著性或扣除交易成本後的可交易性。若要加強結論，應使用新的未見期間或多個事前規劃的預測樣本，而不是回頭調整這 142 筆的規格。</p>
<h2 id="arima-tscv">套件作法：用 <code>Arima()</code> 與 <code>tsCV()</code> 重做滾動預測<a class="headerlink" href="#arima-tscv" title="Permanent link">#</a></h2>
<p>原課程教師程式 <code>slides/L05_Forecasting_and_CV/W1L5_R_prediction_cv.R</code>
使用 <code>forecast::Arima()</code>、<code>forecast::forecast()</code> 與 <code>forecast::tsCV()</code> 處理
估計、預測與時間序列交叉驗證。下列程式沿用原課程的工作流程，但繼續使用本書的固定
CSV 與同一組測試起點，不重新下載 FRED 資料。<code>tsCV()</code> 會替我們依序呼叫預測函數並整理誤差，卻不負責決定模型、視窗或測試期；這些選擇仍沿用前面在驗證期選定的設定。</p>
<p>這裡有一個值得特別注意的估計差異：前面的手動版在每個 250 期視窗使用 OLS 估計
AR(1)；<code>forecast::Arima(..., method = "ML")</code> 則以高斯最大概似估計同一個
AR(1) 規格。兩者使用相同的目標、視窗與資訊時點，預測應當接近，但不必逐期完全相同。</p>
<pre><code class="language-r">stopifnot(requireNamespace(&quot;forecast&quot;, quietly = TRUE))

comparison_window &lt;- 250L
stopifnot(
  selected_model == &quot;rolling_ar1&quot;,
  selected_window == comparison_window
)

package_ar1_forecast &lt;- function(z, h) {
  # z 只含該起點可見的 250 筆；函數內不得再存取外部完整序列。
  fit &lt;- forecast::Arima(
    z,
    order = c(1L, 0L, 0L),
    include.mean = TRUE,
    method = &quot;ML&quot;
  )
  forecast::forecast(fit, h = h)
}

package_forecast_at_origin &lt;- function(y, origin, window) {
  training_start &lt;- origin - window + 1L
  z &lt;- y[training_start:origin]
  # 每個起點重新以 ML 配適，再形成唯一的一步預測。
  fc &lt;- package_ar1_forecast(z, h = 1L)
  data.frame(
    origin = origin,
    target_index = origin + 1L,
    training_start = training_start,
    training_end = origin,
    forecast = as.numeric(fc$mean[1]),
    actual = y[origin + 1L]
  )
}

package_test &lt;- do.call(rbind, lapply(test_origins, function(origin) {
  package_forecast_at_origin(y, origin, comparison_window)
}))
package_test$error &lt;- package_test$actual - package_test$forecast

# tsCV 的第 t 列是以第 t 期為預測起點的誤差；
# window = 250 確保預測函數每次只收到最近 250 筆已知報酬。
package_cv_errors &lt;- forecast::tsCV(
  stats::ts(y),
  forecastfunction = package_ar1_forecast,
  h = 1L,
  window = comparison_window,
  initial = comparison_window
)
package_cv_test &lt;- as.numeric(package_cv_errors)[test_origins]

stopifnot(
  all(is.finite(package_cv_test)),
  max(abs(package_cv_test - package_test$error)) &lt; 1e-10,
  all(package_test$training_end &lt; package_test$target_index)
)

manual_ar1_test &lt;- test_results[
  test_results$model == &quot;rolling_ar1&quot; &amp;
    test_results$window == comparison_window,
]
stopifnot(identical(manual_ar1_test$origin, package_test$origin))

package_comparison &lt;- data.frame(
  方法 = c(
    &quot;手動 OLS：250 期滾動 AR(1)&quot;,
    &quot;forecast：250 期滾動 AR(1) ML&quot;
  ),
  RMSE = c(
    sqrt(mean(manual_ar1_test$error^2)),
    sqrt(mean(package_test$error^2))
  ),
  MAE = c(
    mean(abs(manual_ar1_test$error)),
    mean(abs(package_test$error))
  ),
  平均誤差 = c(
    mean(manual_ar1_test$error),
    mean(package_test$error)
  ),
  check.names = FALSE
)
knitr::kable(package_comparison, digits = 7)
</code></pre>
<table>
<thead>
<tr>
<th style="text-align: left;">方法</th>
<th style="text-align: right;">RMSE</th>
<th style="text-align: right;">MAE</th>
<th style="text-align: right;">平均誤差</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align: left;">手動 OLS：250 期滾動 AR(1)</td>
<td style="text-align: right;">0.0081441</td>
<td style="text-align: right;">0.0060522</td>
<td style="text-align: right;">0.0005755</td>
</tr>
<tr>
<td style="text-align: left;">forecast：250 期滾動 AR(1) ML</td>
<td style="text-align: right;">0.0081438</td>
<td style="text-align: right;">0.0060516</td>
<td style="text-align: right;">0.0005755</td>
</tr>
</tbody>
</table>
<pre><code class="language-r">forecast_difference &lt;- data.frame(
  逐期預測差異指標 = c(&quot;平均絕對差&quot;, &quot;最大絕對差&quot;),
  數值 = c(
    mean(abs(manual_ar1_test$forecast - package_test$forecast)),
    max(abs(manual_ar1_test$forecast - package_test$forecast))
  ),
  check.names = FALSE
)
knitr::kable(forecast_difference, digits = 9)
</code></pre>
<table>
<thead>
<tr>
<th style="text-align: left;">逐期預測差異指標</th>
<th style="text-align: right;">數值</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align: left;">平均絕對差</td>
<td style="text-align: right;">1.0473e-05</td>
</tr>
<tr>
<td style="text-align: left;">最大絕對差</td>
<td style="text-align: right;">3.8143e-05</td>
</tr>
</tbody>
</table>
<p>比較表中的手動 OLS 與套件 ML 分數若很接近，表示兩種估計法在這段資料上的逐期預測差異不大；<code>forecast_difference</code> 則把平均與最大預測差直接量化。<code>tsCV()</code> 在這裡不負責選模，250 期視窗已經由驗證期選定；它只是用套件重做同一組滾動起點，並確認誤差與逐起點迴圈一致。若先用全樣本 <code>auto.arima()</code> 選好模型，再對早期起點執行 <code>tsCV()</code>，未來的選模資訊仍會被帶回過去。</p>
<h2 id="_6">預測路徑與累積損失<a class="headerlink" href="#_6" title="Permanent link">#</a></h2>
<p>總分會把 142 筆誤差濃縮成一個數字，卻看不出差距在哪些日期形成。上圖把實際值與四條預測放在一起，下圖累加每一期平方誤差；每次陡升都代表某個目標日對最終 RMSE 有較大影響。</p>
<pre><code class="language-r">model_labels &lt;- unique(test_results$model_label)
colors &lt;- c(&quot;#173B57&quot;, &quot;#A34045&quot;, &quot;#1D6D73&quot;, &quot;#8A6D3B&quot;)

old_par &lt;- par(
  mfrow = c(2, 1), mar = c(4.5, 4, 3, 1),
  family = plot_family
)
actual_path &lt;- test_results[test_results$model_label == model_labels[1], ]
plot(
  actual_path$target_date, 100 * actual_path$actual,
  type = &quot;l&quot;, col = &quot;gray55&quot;,
  xlab = &quot;目標日期&quot;, ylab = &quot;日對數報酬（%）&quot;,
  main = &quot;實際值與預測&quot;
)
for (j in seq_along(model_labels)) {
  z &lt;- test_results[test_results$model_label == model_labels[j], ]
  lines(z$target_date, 100 * z$forecast, col = colors[j], lwd = 1.4)
}
legend(
  &quot;topleft&quot;, c(&quot;實際值&quot;, model_labels),
  col = c(&quot;gray55&quot;, colors[seq_along(model_labels)]),
  lty = 1, lwd = c(1, rep(1.4, length(model_labels))),
  bty = &quot;n&quot;, cex = 0.8
)

total_loss &lt;- vapply(
  split(test_results$error, test_results$model_label),
  function(e) sum(e^2), numeric(1)
)
plot(
  actual_path$target_date,
  rep(NA_real_, nrow(actual_path)),
  type = &quot;n&quot;,
  xlim = range(actual_path$target_date),
  ylim = c(0, max(total_loss)),
  xlab = &quot;目標日期&quot;, ylab = &quot;累積平方誤差&quot;,
  main = &quot;累積損失&quot;
)
for (j in seq_along(model_labels)) {
  z &lt;- test_results[test_results$model_label == model_labels[j], ]
  lines(z$target_date, cumsum(z$error^2), col = colors[j], lwd = 2)
}
legend(
  &quot;topleft&quot;, model_labels,
  col = colors[seq_along(model_labels)],
  lty = 1, lwd = 2, bty = &quot;n&quot;, cex = 0.8
)
</code></pre>
<p><img alt="TWD/JPY 測試期的一步預測與累積平方預測誤差。" src="./R06_leak_free_out_of_sample_evaluation_files/figure-gfm/cumulative-loss-1.png"></p>
<pre><code class="language-r">par(old_par)
</code></pre>
<p>累積損失可以定位哪些日期主導 RMSE。若某次跳升來自資料錯誤，就回到來源修正；若是真實匯率變動，則應保留，並承認模型在那類市場狀況下預測較差。極端誤差本身不是刪除觀察值的理由。</p>
<h2 id="_7">逐列確認訓練日期早於預測目標<a class="headerlink" href="#_7" title="Permanent link">#</a></h2>
<p>最後不只相信函數名稱，而是直接用輸出的日期檢查每一列。有效的預測必須同時滿足：訓練終點就是該次預測起點，而且訓練終點早於目標日期。這項檢查若失敗，應先修正索引與日期對齊，再解讀任何分數。</p>
<pre><code class="language-r">leakage_audit &lt;- within(
  test_results[c(
    &quot;model_label&quot;, &quot;origin_date&quot;, &quot;target_date&quot;,
    &quot;training_start_date&quot;, &quot;training_end_date&quot;
  )],
  valid_timing &lt;- training_end_date == origin_date &amp;
    training_end_date &lt; target_date
)

knitr::kable(as.data.frame(table(leakage_audit$valid_timing)))
</code></pre>
<table>
<thead>
<tr>
<th style="text-align: left;">Var1</th>
<th style="text-align: right;">Freq</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align: left;">TRUE</td>
<td style="text-align: right;">568</td>
</tr>
</tbody>
</table>
<pre><code class="language-r">stopifnot(all(leakage_audit$valid_timing))
</code></pre>
<p>列聯表應只出現 <code>TRUE</code>。這確認了目前幾個預測函數的日期時序，但不會自動檢查未來新增的資料轉換；每加入一個步驟，都要重新問它在哪些觀察值上估計。</p>
<p>若未來加入標準化、缺值填補、PCA 或變數選擇，這些轉換也必須放入每個預測起點，只用當時可見的訓練資料配適。先以全樣本估計平均數、主成分或選入變數，再回頭做早期滾動預測，仍會洩漏未來資訊。</p>
<h2 id="_8">這次樣本外比較應如何收束<a class="headerlink" href="#_8" title="Permanent link">#</a></h2>
<p>這份固定 TWD/JPY 資料顯示，驗證期選出的 250 期滾動 AR(1) 在測試期的 RMSE 略低於零報酬基準，手動 OLS 與套件 ML 作法也得到接近的預測分數。由逐列日期可以確認，每次估計只使用起點當時可見的報酬，目標日資料沒有提前進入模型。</p>
<p>目前還不能判定這項小幅優勢能延續到其他匯率時期，也沒有納入即時發布落差、資料修訂、交易成本或模型選擇不確定性。實務上應保存固定資料版本、報價方向、三段日期、候選視窗、驗證分數、規格選定時點與逐起點預測紀錄，再把模型帶到新的未見期間。如果看過本次測試結果後進行敏感度分析，應清楚標示為後續探索，不能取代原先選定規格的主要結果。</p>
      </article>
      <nav class="pager" aria-label="前後附錄"><a rel="prev" href="R05_arma_estimation_diagnostics_forecasting.html">← AAPL 的 ARMA 估計、診斷與預測</a><a rel="next" href="R07_unit_roots_differencing_breaks.html">TWD／JPY 的單根、差分與結構變動 →</a></nav>
      <footer>© 陳釗而　《財務時間序列分析》</footer>
    </main>
    <aside class="page-toc"><h2>本頁目錄</h2><div class="toc">
<ul>
<li><a href="#_1">固定資料與預測目標</a></li>
<li><a href="#_2">依時間固定訓練、驗證與測試期</a></li>
<li><a href="#_3">單一起點的預測函數</a></li>
<li><a href="#_4">驗證期選擇滾動規格</a></li>
<li><a href="#_5">選定規格後的一次性測試</a></li>
<li><a href="#arima-tscv">套件作法：用 Arima() 與 tsCV() 重做滾動預測</a></li>
<li><a href="#_6">預測路徑與累積損失</a></li>
<li><a href="#_7">逐列確認訓練日期早於預測目標</a></li>
<li><a href="#_8">這次樣本外比較應如何收束</a></li>
</ul>
</div>
</aside>
  </div>
</body>
</html>
