<!doctype html>
<html lang="zh-Hant-TW">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="《財務時間序列分析》R 線上附錄：R10：真實股票報酬的 PCA、低秩重建與因子分析">
  <title>R10：真實股票報酬的 PCA、低秩重建與因子分析｜財務時間序列分析</title>
  <link rel="stylesheet" href="assets/site.css">
  <script>
    window.MathJax = {
      tex: {inlineMath: [['$', '$'], ['\\(', '\\)']], displayMath: [['$$', '$$'], ['\\[', '\\]']]},
      svg: {fontCache: 'local'},
      options: {skipHtmlTags: ['script', 'noscript', 'style', 'textarea', 'pre', 'code']}
    };
  </script>
  <script defer src="assets/mathjax-loader.js"></script>
  <script defer src="assets/site.js"></script>
</head>
<body>
  <a class="skip-link" href="#main-content">跳到主要內容</a>
  <header class="site-header">
    <button class="menu-button" type="button" aria-controls="site-navigation" aria-expanded="false">目錄</button>
    <a class="brand" href="index.html"><span>財務時間序列分析</span><small>R 線上附錄</small></a>
    <a class="policy-link" href="data-policy.html">資料說明</a>
  </header>
  <div class="layout">
    <nav id="site-navigation" class="sidebar" aria-label="全部線上附錄">
      <p class="sidebar-title">線上附錄</p>
      <ol><li><a href="index.html">首頁</a></li>
<li><a href="data.html">實證資料下載</a></li>
<li><a href="data-policy.html">資料來源與重現說明</a></li>
<li><a href="R00_environment_reproducibility.html">R00　環境、專案與可重現研究</a></li>
<li><a href="R01_r_tidyverse_manual_ols.html">R01　R、tidyverse 與手動 OLS</a></li>
<li><a href="R02_prices_dates_returns.html">R02　價格、日期與報酬率</a></li>
<li><a href="R03_distributions_heavy_tails.html">R03　分配、厚尾與實證特徵</a></li>
<li><a href="R04_ar_ma_arma_simulation.html">R04　AR、MA、ARMA 與真實報酬的 ACF</a></li>
<li><a href="R05_arma_estimation_diagnostics_forecasting.html">R05　AAPL 的 ARMA 估計、診斷與預測</a></li>
<li><a href="R06_leak_free_out_of_sample_evaluation.html">R06　TWD／JPY 的無資料洩漏樣本外評估</a></li>
<li><a href="R07_unit_roots_differencing_breaks.html">R07　TWD／JPY 的單根、差分與結構變動</a></li>
<li><a href="R08_arch_garch_asymmetry_forecasting.html">R08　AAPL 的 ARCH、GARCH、非對稱波動與預測</a></li>
<li><a href="R09_portfolio_capm_factors.html">R09　美國十產業投資組合、CAPM 與 Fama–French 三因子</a></li>
<li><a href="R10_pca_factor_analysis.html" aria-current="page" class="active">R10　真實股票報酬的 PCA、低秩重建與因子分析</a></li>
<li><a href="R11_sp500_pca_corrected.html">R11　S&amp;P 500 平衡子樣本的 PCA 與跨股票落後值修正</a></li>
<li><a href="R12_taiwan_dcc_icapm_case_study.html">R12　臺灣 DCC–ICAPM 的第二階段個案研究</a></li>
<li><a href="R13_regularization.html">R13　Ridge、LASSO、Elastic Net 與 post-LASSO</a></li>
<li><a href="R14_financial_factor_selection.html">R14　機器學習的金融因子選擇</a></li>
<li><a href="R15_double_selection_dml.html">R15　加州學校資料的雙重選擇與 DML 式殘差化</a></li>
<li><a href="R16_var_irf.html">R16　VAR、識別與衝擊反應函數</a></li>
<li><a href="R17_cointegration_vecm.html">R17　共整合、Johansen 檢定與 VECM</a></li>
<li><a href="R18_local_projection_irf.html">R18　VAR、局部投影與進階 IRF</a></li></ol>
    </nav>
    <main id="main-content" class="content">
      <div class="publication-note">
        想自己重算，可以從頁首下載 R Markdown 與執行結果。所有實證例都使用隨書提供的固定資料；
        檔案來源、變數單位與已知限制請見<a href="data-policy.html">資料來源與重現說明</a>。
      </div>
      <article>
        <header class="article-header"><p class="eyebrow">《財務時間序列分析》線上附錄</p><h1>R10：真實股票報酬的 PCA、低秩重建與因子分析</h1><div class="source-links" aria-label="下載本頁檔案"><a href="source/R10_pca_factor_analysis.Rmd">下載 R Markdown</a><a href="source/R10_pca_factor_analysis.md">下載執行結果（Markdown）</a></div></header>
        <p>五檔股票的報酬可否用少數幾個共同方向近似，而不失去太多橫斷面變動？把維度固定後，這個低秩表示能否延伸到較晚的月份？本附錄先用主成分分析（principal component analysis, PCA）回答這兩題，再用另一組十家公司資料示範：最大概似因子分析如何把每檔股票的標準化變異拆成共同性與個別變異。</p>
<p>五公司資料涵蓋 1990 年 1 月至 2008 年 12 月，共 228 個月；一列是一個月份，一欄是一家公司。十公司 Barra 資料涵蓋 1990 年 1 月至 2003 年 12 月，共 168 個月，資料排列方式相同。數值沿用原課程檔，以<strong>月報酬百分點</strong>表示，例如 4.5 代表約 4.5%；五公司檔記錄月對數報酬。資料來自原課程指向的 Ruey S. Tsay／Chicago Booth 教材檔案，隨書提供兩份固定的整理後 CSV，讓讀者可離線重做。若由上游教材檔重新整理，請保存教材版本與下載日。</p>
<p>PCA 與因子分析在這裡都用來描述共同變動。PCA 的跨期重建仍使用目標月份五檔股票的同月報酬來計算分數，因而不是前一期預測；旋轉後的統計因子也不會自動取得經濟名稱或因果意義。最後的合成低秩資料只檢查程式能否找回已知共同部分，不作為實證結果。</p>
<p>原課程程式
<code>slides/L09_Statistical_factor_models/W2L4_hands-on_R_factors/R_script_for_factor_analysis.R</code>
已直接使用 <code>stats::prcomp()</code>（原檔第 38–54 行）與 <code>stats::factanal()</code>（第 62–78 行）；
以下保留相同的套件作法。<code>prcomp()</code> 代為處理中心化、標準化與奇異值分解，
<code>factanal()</code> 代為處理最大概似估計與旋轉；研究者仍須決定尺度、保留維度、旋轉方法、
時間切分，以及如何解讀負荷量。矩陣特徵分解、共同性與個別變異則幫助我們看清楚函數究竟算了什麼。</p>
<pre><code class="language-r">knitr::opts_chunk$set(
  echo = TRUE, message = FALSE, warning = FALSE,
  fig.width = 7, fig.height = 4.3
)
stopifnot(getRversion() &gt;= &quot;4.3.0&quot;)
set.seed(1010)
</code></pre>
<h2 id="_1">先看清楚兩組資料的觀察單位與尺度<a class="headerlink" href="#_1" title="Permanent link">#</a></h2>
<pre><code class="language-r">locate_project_file &lt;- function(relative_path) {
  candidates &lt;- c(
    relative_path,
    file.path(&quot;..&quot;, relative_path),
    file.path(&quot;../..&quot;, relative_path)
  )
  hit &lt;- candidates[file.exists(candidates)]
  if (length(hit) == 0L) stop(&quot;找不到專案檔案：&quot;, relative_path)
  normalizePath(hit[1], mustWork = TRUE)
}

five_file &lt;- locate_project_file(
  &quot;data/processed/tsay_five_stock_monthly_returns_1990_2008.csv&quot;
)
barra_file &lt;- locate_project_file(
  &quot;data/processed/tsay_barra_monthly_returns_1990_2003.csv&quot;
)
manifest_file &lt;- locate_project_file(&quot;data/processed/manifest.csv&quot;)

five &lt;- read.csv(five_file, stringsAsFactors = FALSE, check.names = FALSE)
barra &lt;- read.csv(barra_file, stringsAsFactors = FALSE, check.names = FALSE)
manifest &lt;- read.csv(manifest_file, stringsAsFactors = FALSE)
five$month &lt;- as.Date(five$month)
barra$month &lt;- as.Date(barra$month)
# PCA 與跨期評量依賴時間先後，因此先明確排序再建立索引。
five &lt;- five[order(five$month), ]
barra &lt;- barra[order(barra$month), ]

keys &lt;- c(
  &quot;data/processed/tsay_five_stock_monthly_returns_1990_2008.csv&quot;,
  &quot;data/processed/tsay_barra_monthly_returns_1990_2003.csv&quot;
)
manifest_rows &lt;- manifest[match(keys, manifest$file), , drop = FALSE]

stopifnot(
  nrow(five) == 228L, ncol(five) == 6L,
  nrow(barra) == 168L, ncol(barra) == 11L,
  !anyNA(five), !anyNA(barra),
  identical(unname(tools::md5sum(five_file)), manifest_rows$md5[1]),
  identical(unname(tools::md5sum(barra_file)), manifest_rows$md5[2]),
  all(diff(five$month) &gt; 0), all(diff(barra$month) &gt; 0)
)

rbind(
  data.frame(
    dataset = &quot;Tsay five-stock PCA&quot;,
    first_month = min(five$month), last_month = max(five$month),
    months = nrow(five), stocks = ncol(five) - 1L,
    unit = &quot;monthly log-return percentage points&quot;
  ),
  data.frame(
    dataset = &quot;Tsay Barra factor analysis&quot;,
    first_month = min(barra$month), last_month = max(barra$month),
    months = nrow(barra), stocks = ncol(barra) - 1L,
    unit = &quot;monthly return percentage points&quot;
  )
)
</code></pre>
<pre><code>##                      dataset first_month last_month months stocks
## 1        Tsay five-stock PCA  1990-01-01 2008-12-01    228      5
## 2 Tsay Barra factor analysis  1990-01-01 2003-12-01    168     10
##                                   unit
## 1 monthly log-return percentage points
## 2     monthly return percentage points
</code></pre>
<p>第一張表確認兩份資料各以「月份」為觀察單位，也提醒我們不能把 4.5 誤讀成小數報酬 450%。MD5 核對只用來辨認固定資料版本；若上游教材檔更新，應重新記錄來源與轉換，而不是期待雜湊值不變。</p>
<pre><code class="language-r">data.frame(
  dataset = c(&quot;five-stock&quot;, &quot;Barra ten-stock&quot;),
  original_course_file = c(&quot;m-5clog-9008.txt&quot;, &quot;m-barra-9003.txt&quot;),
  source = c(
    &quot;Ruey S. Tsay, Analysis of Financial Time Series, 3e, Example 9.2&quot;,
    &quot;Ruey S. Tsay, Analysis of Financial Time Series, 3e, Example 9.4&quot;
  ),
  identification_boundary = c(
    &quot;PCA 是共同變動的描述，不識別經濟衝擊&quot;,
    &quot;旋轉負荷量不是已命名或具因果意義的結構因子&quot;
  )
)
</code></pre>
<pre><code>##           dataset original_course_file
## 1      five-stock     m-5clog-9008.txt
## 2 Barra ten-stock     m-barra-9003.txt
##                                                             source
## 1 Ruey S. Tsay, Analysis of Financial Time Series, 3e, Example 9.2
## 2 Ruey S. Tsay, Analysis of Financial Time Series, 3e, Example 9.4
##                      identification_boundary
## 1       PCA 是共同變動的描述，不識別經濟衝擊
## 2 旋轉負荷量不是已命名或具因果意義的結構因子
</code></pre>
<h2 id="prcomp">套件作法：用 <code>prcomp()</code> 找出五檔股票的共同方向<a class="headerlink" href="#prcomp" title="Permanent link">#</a></h2>
<p>五家公司為 IBM、HPQ、INTC、JPM 與 BAC。先依時間固定分成 60% 估計期、20% 驗證期、20% 測試期。估計期決定中心、尺度、負荷量與維度規則；驗證期用來觀察這個規則能否延伸到較晚月份；測試期保留到最後，只評量選定維度後的低秩重建。</p>
<p>原課程用一行 <code>prcomp(..., center = TRUE, scale. = TRUE)</code> 完成估計。標準化使每檔股票先以自己的波動尺度衡量，避免高波動股票只因單位較大就支配第一主成分。緊接著的特徵分解會比較特徵值與前兩個主成分所張成的投影空間，讓讀者看見套件輸出和矩陣計算的關係。</p>
<pre><code class="language-r">X_five &lt;- as.matrix(five[, -1, drop = FALSE])
storage.mode(X_five) &lt;- &quot;double&quot;
n_five &lt;- nrow(X_five)
estimate_end &lt;- floor(0.60 * n_five)
validation_end &lt;- floor(0.80 * n_five)
estimate_id &lt;- seq_len(estimate_end)
validation_id &lt;- (estimate_end + 1L):validation_end
test_id &lt;- (validation_end + 1L):n_five

data.frame(
  sample = c(&quot;估計&quot;, &quot;驗證&quot;, &quot;測試&quot;),
  first_month = five$month[c(min(estimate_id), min(validation_id), min(test_id))],
  last_month = five$month[c(max(estimate_id), max(validation_id), max(test_id))],
  months = c(length(estimate_id), length(validation_id), length(test_id))
)
</code></pre>
<pre><code>##   sample first_month last_month months
## 1   估計  1990-01-01 2001-04-01    136
## 2   驗證  2001-05-01 2005-02-01     46
## 3   測試  2005-03-01 2008-12-01     46
</code></pre>
<p>表中的三段月份不能互換角色。特別是測試期的平均數、標準差或報酬，都不能回頭參與 <code>prcomp()</code> 的中心化與尺度估計。</p>
<pre><code class="language-r">pca_estimate &lt;- prcomp(
  X_five[estimate_id, , drop = FALSE],
  center = TRUE,
  scale. = TRUE
)
eigenvalues &lt;- pca_estimate$sdev^2
PVE &lt;- eigenvalues / sum(eigenvalues)
explained &lt;- data.frame(
  component = seq_along(PVE),
  eigenvalue = eigenvalues,
  PVE = PVE,
  cumulative_PVE = cumsum(PVE)
)
explained
</code></pre>
<pre><code>##   component eigenvalue        PVE cumulative_PVE
## 1         1  2.4976099 0.49952198      0.4995220
## 2         2  1.0830169 0.21660338      0.7161254
## 3         3  0.6193526 0.12387051      0.8399959
## 4         4  0.5114440 0.10228880      0.9422847
## 5         5  0.2885766 0.05771533      1.0000000
</code></pre>
<p>第一主成分解釋估計期約 50.0% 的標準化變異，前兩個合計約 71.6%，前三個則約 84.0%。陡坡圖與累積解釋比例都顯示：一個共同方向很重要，但只保留一個成分會漏掉相當多的橫斷面變動。</p>
<pre><code class="language-r">plot(
  explained$component, explained$eigenvalue,
  type = &quot;b&quot;, pch = 19, col = &quot;#173B57&quot;,
  xlab = &quot;主成分&quot;, ylab = &quot;特徵值&quot;,
  main = &quot;五檔股票月報酬的 PCA&quot;
)
abline(h = 1, lty = 2, col = &quot;#A34045&quot;)
</code></pre>
<p><img alt="五家公司估計期相關矩陣的陡坡圖。" src="./R10_pca_factor_analysis_files/figure-gfm/scree-plot-1.png"></p>
<h3 id="prcomp_1">為什麼 <code>prcomp()</code> 與直接特徵分解會得到同一空間？<a class="headerlink" href="#prcomp_1" title="Permanent link">#</a></h3>
<pre><code class="language-r">Z_estimate &lt;- scale(
  X_five[estimate_id, , drop = FALSE],
  center = pca_estimate$center,
  scale = pca_estimate$scale
)
eigen_direct &lt;- eigen(cov(Z_estimate), symmetric = TRUE)
stopifnot(isTRUE(all.equal(
  unname(eigenvalues), unname(eigen_direct$values), tolerance = 1e-10
)))

projection_prcomp &lt;- tcrossprod(pca_estimate$rotation[, 1:2, drop = FALSE])
projection_eigen &lt;- tcrossprod(eigen_direct$vectors[, 1:2, drop = FALSE])
data.frame(
  largest_eigenvalue_difference = max(abs(eigenvalues - eigen_direct$values)),
  two_component_projection_difference =
    max(abs(projection_prcomp - projection_eigen))
)
</code></pre>
<pre><code>##   largest_eigenvalue_difference two_component_projection_difference
## 1                  2.220446e-15                        6.938894e-16
</code></pre>
<p>兩種方法的特徵值與二維投影差異都只在浮點數誤差範圍。主成分向量乘以 $-1$ 仍代表同一條軸，因此比較時應看投影空間或重建結果，而不是把某一個負荷量的正負號當成唯一識別。</p>
<h2 id="_2">三個主成分能否重建較晚月份？<a class="headerlink" href="#_2" title="Permanent link">#</a></h2>
<p>維度選擇先寫成一條可重複的規則：取估計期累積解釋比例達 80% 的最小維度。這份資料選出三個主成分，估計期累積解釋比例約 84.0%。驗證期只用來觀察重建品質，不因結果好壞再修改 80% 門檻。</p>
<pre><code class="language-r">r_selected &lt;- which(explained$cumulative_PVE &gt;= 0.80)[1]
data.frame(
  selected_components = r_selected,
  training_cumulative_PVE = explained$cumulative_PVE[r_selected]
)
</code></pre>
<pre><code>##   selected_components training_cumulative_PVE
## 1                   3               0.8399959
</code></pre>
<pre><code class="language-r">reconstruct_from_pca &lt;- function(fit, newdata, r) {
  # 新月份沿用估計期中心、尺度與負荷量，避免把未來分配資訊帶回模型。
  Z &lt;- scale(newdata, center = fit$center, scale = fit$scale)
  V &lt;- fit$rotation[, seq_len(r), drop = FALSE]
  Z_hat &lt;- (Z %*% V) %*% t(V)
  X_hat &lt;- sweep(Z_hat, 2, fit$scale, &quot;*&quot;)
  list(
    standardized_actual = Z,
    standardized_reconstructed = Z_hat,
    original_reconstructed = sweep(X_hat, 2, fit$center, &quot;+&quot;)
  )
}

reconstruction_score &lt;- function(actual, reconstruction) {
  Z &lt;- reconstruction$standardized_actual
  Z_hat &lt;- reconstruction$standardized_reconstructed
  c(
    original_scale_MSE = mean(
      (actual - reconstruction$original_reconstructed)^2
    ),
    standardized_MSE = mean((Z - Z_hat)^2),
    standardized_fraction_reconstructed =
      1 - sum((Z - Z_hat)^2) / sum(Z^2)
  )
}

validation_reconstruction &lt;- reconstruct_from_pca(
  pca_estimate, X_five[validation_id, , drop = FALSE], r_selected
)
validation_score &lt;- reconstruction_score(
  X_five[validation_id, , drop = FALSE], validation_reconstruction
)
validation_score
</code></pre>
<pre><code>##                  original_scale_MSE                    standardized_MSE 
##                          15.6180780                           0.1232204 
## standardized_fraction_reconstructed 
##                           0.8640172
</code></pre>
<p>評分沿用估計期的中心與尺度，在標準化空間比較實現值 \(Z\) 與重建值 \(\widehat Z\)。這樣估計期的 80% 選維規則與較晚月份的重建比例使用同一尺度；原始百分點 MSE 另列一欄，不能和解釋變異比例混為一談。三成分在驗證期重建約 86.4% 的標準化變動，顯示估計期找到的低維空間並未在下一段月份立即失效。這是同月重建品質，不是報酬方向的預測準確率。</p>
<p>選定三個成分後，以估計期加驗證期重新估計一次 PCA，再只在最後測試期評量。重新估計可利用較多歷史月份更新中心、尺度與負荷量，但不改變已選好的維度。</p>
<pre><code class="language-r">development_id &lt;- c(estimate_id, validation_id)
pca_development &lt;- prcomp(
  X_five[development_id, , drop = FALSE],
  center = TRUE, scale. = TRUE
)
test_reconstruction &lt;- reconstruct_from_pca(
  pca_development, X_five[test_id, , drop = FALSE], r_selected
)
test_score &lt;- reconstruction_score(
  X_five[test_id, , drop = FALSE], test_reconstruction
)
data.frame(
  selected_components = r_selected,
  validation_original_scale_MSE =
    unname(validation_score[&quot;original_scale_MSE&quot;]),
  test_original_scale_MSE = unname(test_score[&quot;original_scale_MSE&quot;]),
  validation_standardized_fraction =
    unname(validation_score[&quot;standardized_fraction_reconstructed&quot;]),
  test_standardized_fraction =
    unname(test_score[&quot;standardized_fraction_reconstructed&quot;])
)
</code></pre>
<pre><code>##   selected_components validation_original_scale_MSE test_original_scale_MSE
## 1                   3                      15.61808                 12.4048
##   validation_standardized_fraction test_standardized_fraction
## 1                        0.8640172                  0.8609249
</code></pre>
<p>測試期原始百分點 MSE 約為 12.40，在與選維規則一致的標準化尺度上，重建比例約為 86.1%。請再次注意，程式先看到目標月份五檔股票的同月報酬，才計算該月主成分分數與重建；它回答「少數共同方向能保留多少同月資訊」，不是以前一期資訊預測下一期報酬。</p>
<h2 id="factanal">套件作法：用 <code>factanal()</code> 分解共同性與個別變異<a class="headerlink" href="#factanal" title="Permanent link">#</a></h2>
<p>第二個問題改用 Barra 十公司資料：三個潛在因子可以解釋每檔股票多少標準化變異，剩下多少屬於個別變異？<code>factanal()</code> 的最大概似因子分析正好提供這個分解。以下使用完整的 1990–2003 年樣本估計三因子並作 varimax 旋轉；這一節是全樣本描述，沒有訓練／測試切分，也不評估保留期績效。</p>
<p>原課程直接使用這個高階函數。它代為處理最大概似最佳化、三因子負荷量與 varimax 旋轉；研究者仍須事先決定因子數、資料尺度與旋轉方式，並檢查解是否容易受到樣本或規格影響。<code>fa_three$loadings</code> 是旋轉後負荷量，<code>fa_three$uniquenesses</code> 是個別變異，兩者合起來提供下表的共同性分解。<code>factanal()</code> 預設不讓個別變異低於 0.005；若估計值剛好停在這個下界，就屬於 Heywood／近 Heywood 警訊，不能把共同性與名目配適檢定照一般內點解解讀。</p>
<pre><code class="language-r">X_barra &lt;- as.matrix(barra[, -1, drop = FALSE])
storage.mode(X_barra) &lt;- &quot;double&quot;
fa_three &lt;- factanal(
  X_barra,
  factors = 3,
  rotation = &quot;varimax&quot;,
  scores = &quot;regression&quot;,
  lower = 0.005
)
loadings_matrix &lt;- unclass(fa_three$loadings)

factor_summary &lt;- data.frame(
  stock = rownames(loadings_matrix),
  communality = rowSums(loadings_matrix^2),
  uniqueness = fa_three$uniquenesses,
  at_lower_bound = abs(fa_three$uniquenesses - 0.005) &lt; 1e-7
)
round(loadings_matrix, 3)
</code></pre>
<pre><code>##      Factor1 Factor2 Factor3
## AGE    0.678   0.217   0.121
## C      0.740   0.258   0.213
## MWD    0.818   0.356   0.062
## MER    0.819   0.328   0.070
## DELL   0.103   0.547   0.019
## HPQ    0.231   0.771   0.080
## IBM    0.200   0.514   0.239
## AA     0.195   0.545   0.499
## CAT    0.199   0.137   0.968
## PG     0.331  -0.018   0.070
</code></pre>
<pre><code class="language-r">factor_summary
</code></pre>
<pre><code>##      stock communality uniqueness at_lower_bound
## AGE    AGE   0.5213440  0.4786595          FALSE
## C        C   0.6590180  0.3409821          FALSE
## MWD    MWD   0.7989332  0.2010671          FALSE
## MER    MER   0.7836121  0.2163876          FALSE
## DELL  DELL   0.3098410  0.6901433          FALSE
## HPQ    HPQ   0.6547619  0.3452369          FALSE
## IBM    IBM   0.3616132  0.6383908          FALSE
## AA      AA   0.5835561  0.4164444          FALSE
## CAT    CAT   0.9950005  0.0050000           TRUE
## PG      PG   0.1150995  0.8848912          FALSE
</code></pre>
<pre><code class="language-r">data.frame(
  nominal_likelihood_ratio_p = fa_three$PVAL,
  minimum_uniqueness = min(fa_three$uniquenesses),
  boundary_stocks = paste(
    names(fa_three$uniquenesses)[factor_summary$at_lower_bound],
    collapse = &quot;, &quot;
  )
)
</code></pre>
<pre><code>##           nominal_likelihood_ratio_p minimum_uniqueness boundary_stocks
## objective                 0.08890732              0.005             CAT
</code></pre>
<p>PG 的共同性約為 0.12，表示大部分變異仍留在個別成分。CAT 看似接近 1，卻是因為個別變異剛好停在 0.005 下界；合宜的說法不是「三因子幾乎完整解釋 CAT」，而是「CAT 產生邊界解，普通三因子規格可能不足或資料不符合一般最大概似條件」。輸出的 0.089 只能稱為在獨立同分配多變量常態、內點解參考下的<strong>名目</strong> $p$ 值；邊界解、厚尾與時間相依都會使這個參考分配變得脆弱。</p>
<p>接著同時改變因子數與個別變異下界。若 CAT 的個別變異總是貼著人為設定的下界，便表示「CAT 共同性接近 1」不是穩健的實證結論。這張表是規格敏感度檢查，不是正式的因子數選擇檢定。</p>
<pre><code class="language-r">factor_sensitivity &lt;- do.call(rbind, lapply(2:4, function(k) {
  do.call(rbind, lapply(c(0.001, 0.005, 0.010), function(lower_bound) {
    fit &lt;- factanal(
      X_barra, factors = k, rotation = &quot;varimax&quot;,
      lower = lower_bound
    )
    data.frame(
      因子數 = k,
      個別變異下界 = lower_bound,
      CAT個別變異 = unname(fit$uniquenesses[&quot;CAT&quot;]),
      CAT共同性 = 1 - unname(fit$uniquenesses[&quot;CAT&quot;]),
      CAT是否貼住下界 =
        abs(unname(fit$uniquenesses[&quot;CAT&quot;]) - lower_bound) &lt; 1e-7,
      名目配適p值 = fit$PVAL,
      check.names = FALSE
    )
  }))
}))
factor_sensitivity
</code></pre>
<pre><code>##             因子數 個別變異下界 CAT個別變異 CAT共同性 CAT是否貼住下界
## objective        2        0.001   0.5969104 0.4030896           FALSE
## objective1       2        0.005   0.5969104 0.4030896           FALSE
## objective2       2        0.010   0.5969104 0.4030896           FALSE
## objective3       3        0.001   0.0010000 0.9990000            TRUE
## objective11      3        0.005   0.0050000 0.9950000            TRUE
## objective21      3        0.010   0.0100000 0.9900000            TRUE
## objective4       4        0.001   0.0010000 0.9990000            TRUE
## objective12      4        0.005   0.0050000 0.9950000            TRUE
## objective22      4        0.010   0.0100000 0.9900000            TRUE
##              名目配適p值
## objective   2.463529e-06
## objective1  2.463529e-06
## objective2  2.463529e-06
## objective3  8.918147e-02
## objective11 8.890732e-02
## objective21 8.855654e-02
## objective4  2.827231e-01
## objective12 2.815853e-01
## objective22 2.801487e-01
</code></pre>
<p>兩因子時 CAT 沒有碰到下界，但名目配適檢定明顯較差；三、四因子時 CAT 又隨設定的下界移動。這說明因子數增加改善整體近似的同時，也暴露 CAT 的邊界問題。因而後面的負荷量圖只用來探索共同變動圖樣，不把 CAT 的共同性當成精確估計，也不宣稱三因子已通過正式模型檢定。</p>
<pre><code class="language-r">decomposition_gap &lt;- max(abs(
  factor_summary$communality + factor_summary$uniqueness - 1
))

stopifnot(
  inherits(pca_estimate, &quot;prcomp&quot;),
  inherits(fa_three, &quot;factanal&quot;),
  decomposition_gap &lt; 5e-4
)

data.frame(
  分析工作 = c(&quot;主成分分析&quot;, &quot;最大概似因子分析&quot;),
  原課程套件寫法 = c(
    &quot;stats::prcomp(center = TRUE, scale. = TRUE)&quot;,
    &quot;stats::factanal(factors = 3, rotation = 'varimax')&quot;
  ),
  本頁物件 = c(&quot;pca_estimate&quot;, &quot;fa_three&quot;),
  核對內容 = c(
    &quot;特徵值與兩主成分投影，對照直接使用 eigen() 的結果&quot;,
    &quot;旋轉後負荷量、共同性、個別變異與配適統計量&quot;
  ),
  數值核對 = c(
    sprintf(
      &quot;最大特徵值差距 = %.3e&quot;,
      max(abs(eigenvalues - eigen_direct$values))
    ),
    sprintf(&quot;最大 |共同性 + 個別變異 - 1| = %.3e&quot;, decomposition_gap)
  ),
  check.names = FALSE
)
</code></pre>
<pre><code>##           分析工作                                     原課程套件寫法
## 1       主成分分析        stats::prcomp(center = TRUE, scale. = TRUE)
## 2 最大概似因子分析 stats::factanal(factors = 3, rotation = 'varimax')
##       本頁物件                                          核對內容
## 1 pca_estimate 特徵值與兩主成分投影，對照直接使用 eigen() 的結果
## 2     fa_three        旋轉後負荷量、共同性、個別變異與配適統計量
##                                   數值核對
## 1               最大特徵值差距 = 2.220e-15
## 2 最大 |共同性 + 個別變異 - 1| = 1.565e-05
</code></pre>
<pre><code class="language-r">barplot(
  t(abs(loadings_matrix)), beside = TRUE,
  col = c(&quot;#173B57&quot;, &quot;#A34045&quot;, &quot;#1D6D73&quot;),
  names.arg = rownames(loadings_matrix),
  las = 2, ylab = &quot;因子負荷量絕對值&quot;,
  main = &quot;十家公司月報酬的旋轉後負荷量&quot;
)
legend(
  &quot;topright&quot;, paste0(&quot;因子 &quot;, 1:3),
  fill = c(&quot;#173B57&quot;, &quot;#A34045&quot;, &quot;#1D6D73&quot;), bty = &quot;n&quot;
)
</code></pre>
<p><img alt="Barra 十公司三因子 varimax 旋轉後的絕對負荷量。" src="./R10_pca_factor_analysis_files/figure-gfm/loading-plot-1.png"></p>
<p>旋轉使負荷量更容易呈現群組：前兩個因子分別在部分金融與科技公司上較高，第三因子明顯集中於 CAT。這些圖樣可協助描述共同變動，但公司名稱與統計負荷量本身不足以把因子命名為特定產業、風險或結構性衝擊；命名需要額外變數與可檢驗的經濟論證。</p>
<h2 id="_3">已知真值時，兩個主成分能找回共同部分嗎？<a class="headerlink" href="#_3" title="Permanent link">#</a></h2>
<p>模擬只用於確認「保留正確共同維度可以接近真共同部分」的程式性質，不作實證結論。</p>
<pre><code class="language-r">set.seed(1010)
n_sim &lt;- 600L
F_true &lt;- matrix(rnorm(n_sim * 2L), ncol = 2L)
B_true &lt;- rbind(
  c(0.9, 0.1), c(0.8, 0.2), c(0.7, 0.1),
  c(0.1, 0.9), c(0.2, 0.8), c(0.1, 0.7)
)
common_true &lt;- F_true %*% t(B_true)
X_sim &lt;- common_true + matrix(rnorm(n_sim * 6L, sd = 0.15), ncol = 6L)
pc_sim &lt;- prcomp(X_sim, center = TRUE, scale. = FALSE)
common_hat_centered &lt;-
  pc_sim$x[, 1:2, drop = FALSE] %*% t(pc_sim$rotation[, 1:2, drop = FALSE])
common_true_centered &lt;- scale(common_true, center = TRUE, scale = FALSE)
common_correlation &lt;- cor(
  as.vector(common_true_centered), as.vector(common_hat_centered)
)
stopifnot(common_correlation &gt; 0.95)
data.frame(
  true_rank = 2L,
  retained_components = 2L,
  correlation_with_true_common_part = common_correlation
)
</code></pre>
<pre><code>##   true_rank retained_components correlation_with_true_common_part
## 1         2                   2                         0.9944641
</code></pre>
<p>相關係數高於 0.95，說明這段程式在訊號強、維度已知的設計下能抓到共同部分。這只是程式與直覺的單元檢查；真實資料沒有可觀察的「真共同部分」，所以不能把模擬成功當成實證模型正確的證明。</p>
<h2 id="_4">從降維結果回到研究目的<a class="headerlink" href="#_4" title="Permanent link">#</a></h2>
<p>五公司資料顯示，三個主成分在較晚的測試月份仍可重建約八成以上的同月標準化變動。評分與估計期的選維規則採同一尺度；原始百分點 MSE 則另行報告。若研究目的只是壓縮資料或建立低秩共變異數近似，這是有用的起點；若目的是預測，則要另外設計只使用預測形成時已知資訊的因子分數或動態模型。</p>
<p>十公司因子分析則顯示，共同性在公司之間差異很大；CAT 的個別變異碰到 <code>factanal()</code> 下界，不能把接近 1 的共同性當成精確證據，名目配適 $p$ 值也不足以宣告三因子模型成立。旋轉讓圖樣容易閱讀，卻沒有解決邊界解、因子命名與結構識別。下一步可以比較不同因子數、旋轉方法與分段樣本，並以區塊拔靴或其他能反映時間相依的程序檢查穩定性。</p>
<p>重做時請保留月百分點尺度、教材版本與時間切分。若把資料先轉成小數，所有 MSE 數值會隨尺度平方改變，但解釋比例與主成分空間不應因此被重新賦予不同經濟意義。</p>
<pre><code class="language-r">sessionInfo()
</code></pre>
<pre><code>## R version 4.5.2 (2025-10-31)
## Platform: aarch64-apple-darwin20
## Running under: macOS Tahoe 26.5.1
## 
## Matrix products: default
## BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib 
## LAPACK: /Library/Frameworks/R.framework/Versions/4.5-arm64/Resources/lib/libRlapack.dylib;  LAPACK version 3.12.1
## 
## locale:
## [1] C.UTF-8/C.UTF-8/C.UTF-8/C/C.UTF-8/C.UTF-8
## 
## time zone: Asia/Tokyo
## tzcode source: internal
## 
## attached base packages:
## [1] stats     graphics  grDevices utils     datasets  methods   base     
## 
## loaded via a namespace (and not attached):
##  [1] Matrix_1.7-4        gtable_0.3.6        dplyr_1.2.1        
##  [4] compiler_4.5.2      gbutils_0.5.1       fBasics_4052.98    
##  [7] tidyselect_1.2.1    Rcpp_1.1.0          cvar_0.6           
## [10] parallel_4.5.2      systemfonts_1.3.2   scales_1.4.0       
## [13] timeSeries_4052.112 textshaping_1.0.5   lattice_0.22-7     
## [16] ggplot2_4.0.3       R6_2.6.1            generics_0.1.4     
## [19] fGarch_4052.93      knitr_1.51          rbibutils_2.4.1    
## [22] tibble_3.3.0        spatial_7.3-18      forecast_9.0.2     
## [25] timeDate_4052.112   pillar_1.11.1       RColorBrewer_1.1-3 
## [28] rlang_1.1.7         urca_1.3-4          xfun_0.57          
## [31] S7_0.2.2            otel_0.2.0          cli_3.6.5          
## [34] magrittr_2.0.4      Rdpack_2.6.6        grid_4.5.2         
## [37] lifecycle_1.0.5     nlme_3.1-168        fracdiff_1.5-4     
## [40] vctrs_0.7.2         evaluate_1.0.5      glue_1.8.0         
## [43] farver_2.1.2        ragg_1.5.2          zoo_1.8-15         
## [46] colorspace_2.1-3    tools_4.5.2         pkgconfig_2.0.3
</code></pre>
      </article>
      <nav class="pager" aria-label="前後附錄"><a rel="prev" href="R09_portfolio_capm_factors.html">← 美國十產業投資組合、CAPM 與 Fama–French 三因子</a><a rel="next" href="R11_sp500_pca_corrected.html">S&amp;P 500 平衡子樣本的 PCA 與跨股票落後值修正 →</a></nav>
      <footer>© 陳釗而　《財務時間序列分析》</footer>
    </main>
    <aside class="page-toc"><h2>本頁目錄</h2><div class="toc">
<ul>
<li><a href="#_1">先看清楚兩組資料的觀察單位與尺度</a></li>
<li><a href="#prcomp">套件作法：用 prcomp() 找出五檔股票的共同方向</a><ul>
<li><a href="#prcomp_1">為什麼 prcomp() 與直接特徵分解會得到同一空間？</a></li>
</ul>
</li>
<li><a href="#_2">三個主成分能否重建較晚月份？</a></li>
<li><a href="#factanal">套件作法：用 factanal() 分解共同性與個別變異</a></li>
<li><a href="#_3">已知真值時，兩個主成分能找回共同部分嗎？</a></li>
<li><a href="#_4">從降維結果回到研究目的</a></li>
</ul>
</div>
</aside>
  </div>
</body>
</html>
